@startuml US15_DM
hide methods
skinparam classAttributeIconSize 0

class Company {
  -designation
}

class CenterCoordinator {}

class Employee {
  -name
  -phoneNumber
  -email
  -password
  -address
  -citizenCardNumber
  -roleId
}

class VaccinationCenter{
  -name
  -address
  -emailAddress
  -phoneNumber
  -faxNumber
  -websiteAddress
  -time
  -slot
  -coordinator
}

class Time {
  -hours
  -minutes
}

class Slot {
  -slotDuration
  -maxVacPerSlot
}

class VaccineAdministration {
  -snsUser
  -vaccine
  -dose
  -lotNumber
  -date
}

class SNSUser {
  - citizenCard
  - snsNumber
  - name
  - birthDay
  - gender
  - phoneNumber
  - email
  - address
}

class ReportFile {}

class Vaccine {}

class VaccineType {
  -code 
  -description
  -technology
}

Company "1" -- "*" Employee : knows >
Employee <|-- CenterCoordinator
CenterCoordinator -- VaccinationCenter : has >
VaccinationCenter "1" -- "1" Time : has >
VaccinationCenter "1"-- "1" Slot : has >
ReportFile "1" -- "1" CenterCoordinator : generates <
VaccineAdministration "*" -- "1" VaccinationCenter : has <
VaccineAdministration "1" -- "*" SNSUser : has >
VaccineAdministration "1" -- "1" Vaccine : has > 
Vaccine -- VaccineType : has >
Company "1" -- "*" VaccinationCenter : knows >

@enduml