@startuml US10_SD
autonumber
'hide footbox
actor "Admininistrator" as admin

participant ":CreateEmployeeUi" as empUi
participant ":CreateEmployeeController" as empController
participant "role\n:Role" as role
participant "comp\n:Company" as comp
participant ":Employee" as emp

activate admin
admin -> empUi : asks to create a new employee
activate empUi
empUi --> admin : requests data (name, email, password)
deactivate empUi

admin -> empUi : types requested data
activate empUi

empUi -> empController : roleList=getEmployeeRoles()
activate empController

empController -> comp : roleList=getEmployeeRoles()
activate comp
|||
deactivate comp
deactivate empController

empUi --> admin : shows user roles list and asks to select one
deactivate empUi

admin -> empUi : selects a user role
activate empUi

empUi -> empController : createEmployee(name, email, password, roleId)
activate empController

empController -> role : role=getRoleById(roleId)
activate role
|||
deactivate role

empController -> comp: employee=createEmployee(name, email, password, role)
activate comp

comp --> emp**: create(name, email, password, role)
comp -> comp: validateEmployee(employee)
empController --> empUi: result
empUi --> admin: shows all data and requests confirmation
deactivate comp
deactivate empController
deactivate empUi

admin -> empUi : confirms the data
activate empUi
empUi -> empController : saveEmployee()
activate empController

empController -> comp : saveEmployee(employee)
activate comp

comp -> comp: validateEmployee(employee)
|||
comp -> comp: addEmployee(employee)
|||

empController --> empUi: result

empUi --> admin : informs operation success
deactivate comp
deactivate empController
deactivate empUi

deactivate admin

@enduml