@startuml Class Diagram
skinparam classAttributeIconSize 0

class ApplicationPOT {
  + static getInstance()
  + getCurrentSession()
}

class Company {
  - String designation
  + validateUser(user)
  + createUser(snsNumber, name, email, birthDate, phoneNumber)
}

class RegisterSNSUserController {
  + getUsers()
  + getUser(userId)
}

class RegisterSNSUserUI { }

class SNSUser {
  - String snsNumber
  - String name
  - Date birthDate
  - Char gender
  - String phoneNumber
  - String email
  + SNSUser(snsNumber, name, birthDate, gender, phoneNumber, email)
}

interface User {
  - String name
  - String email
  - String pwd
  - String roleId
}

' class UserSession {
'   + getUserEmail()
' }

Company "1" --> "*" SNSUser : knows

RegisterSNSUserController ..> ApplicationPOT
RegisterSNSUserController ..> Company
RegisterSNSUserController ..> SNSUser
' RegisterSNSUserController ..> UserSession

RegisterSNSUserUI ..> RegisterSNSUserController

SNSUser --|> User

@enduml