@startuml Class Diagram
skinparam classAttributeIconSize 0

class ApplicationPOT {
  + static getInstance()
  + getCurrentSession()
}

class Company {
  - String designation
  + validateUser(user)
  + createUser(snsNumber, name, email, birthDate, phoneNumber)
}

class RegisterSNSUserController {
  + getUsers()
  + getUser(userId)
}

class RegisterSNSUserUI { }

class SNSUser {
  - String SNSNumber
  - String name
  - Date birthDate
  - Char gender
  - Integer phoneNumber
  - String email
  + SNSUser(ref,designation,informalDesc,technicalDesc,duration,cost,cat)
}

interface User {
  - String name
  - String email
  - String pwd
  - String role
}

' class UserSession {
'   + getUserEmail()
' }

RegisterSNSUserController ..> ApplicationPOT
RegisterSNSUserController ..> Company
RegisterSNSUserController ..> SNSUser
' RegisterSNSUserController ..> UserSession

RegisterSNSUserUI ..> RegisterSNSUserController

SNSUser ..> User

@enduml