@startuml
skinparam classAttributeIconSize 0

class Arrive {
  - Date arriveTime
  - int status
}

class NurseSession {
  - String nurseName
  - String vaccinationCenterId

  + NurseSession(String nurseName, String vaccinationCenterId)
  + String getVaccinationCenterId()
}

class Company {
  -designation: String
  -authFacade: AuthFacade
  -vaccinationCenterStore: VaccinationCenterStore
  
  +Company(designation)

  +getAuthFacade()
  +getVaccinationCenterStore()
}

class CheckWaitingRoomController {
  +getCategories()
  +CheckWaitingRoom(ref,designation,informalDesc,technicalDesc,duration,cost,categoryId)
  +saveTask()
}

class CheckWaitingRoomUI {}

class VaccinationCenter {
  - name: String
  - address: String
  - emailAddress: String
  - phoneNumber: String
  - faxNumber: String
  - websiteAddress: String
  - openingHours: String
  - closingHours: String
  - slotDuration: int
  - maximumVaccinesPerSlot: int
  
  +VaccinationCenter(name,address,emailAddress,phoneNumber,faxNumber,websiteAddress,openingHours,closingHours,slotDuration,maximumVaccinesPerSlot,coordinator)
}

class VaccinationCenterStore {
+createVaccinationCenter(centerData,coordinator)
+validateVaccinatonCenter(center)
+saveVaccinationCenter(center)
+checkDuplicates(center)

-addVaccinationCenter(center)
}

class Employee {
  -id: String 
  -name: String 
  -email: String 
  -phone: String 
  -address: String 
  -citizenCardNumber: int 
  -roleId: String 

  +Employee(name,email,phone,address,citizenCardNumber,roleId)
}

class SNSUser {
  - String citizenCard
  - String snsNumber
  - Date birthDay
  - Char gender
  - String phoneNumber
  - String address
  + SNSUser(citizenCard, snsNumber, name, birthDay, gender, phoneNumber, email, address)
}

class WaitingRoomList {
  +createArrive(arriveTime, user, appointment)
  +saveArrive(arrive)
  +removeArrive(arrive)
  -checkDuplicates(arrive)
}

class Appointment {
  -Date appointmentDate

  +Appointment(appointmentDate, user, vaccine)
}

class Vaccine{
  -designation : String
  -brand : String
  -id : String
  -vacType : VaccineType

  +Vaccine(designation, id, brand, vacTypeId)
}

CheckWaitingRoomUI ..> CheckWaitingRoomController
CheckWaitingRoomController ..> Company

Arrive o-- SNSUser
Arrive o-- Appointment
Appointment o-- SNSUser

VaccinationCenter o-- Employee : coordinator
VaccinationCenterStore "1" -- "*" VaccinationCenter : stores >

Company ..> VaccinationCenterStore

WaitingRoomList "1" -- "*" Arrive : stores >

Employee "1" -- "*" WaitingRoomList : checks
VaccinationCenter *-- WaitingRoomList

CheckWaitingRoomController ..> NurseSession

Appointment "*" -- "1" VaccinationCenter : has <
Appointment o-- Vaccine

@enduml
