@startuml US10_SSD
autonumber
actor "Administrator" as admin

activate admin
admin -> ":System" : asks to register a new empolyee
activate ":System"
":System" --> admin : requests data (name, email, password, etc)
deactivate ":System"

admin -> ":System" : types requested data
activate ":System"
":System" --> OE : shows user roles list and asks to select one
deactivate ":System"

OE -> ":System" : selects a user role
activate ":System"
":System" --> admin : shows all data and requests confirmation
deactivate ":System"

admin -> ":System" : confirms the data
activate ":System"
":System" --> admin : informs operation success
deactivate ":System"

deactivate admin

@enduml