@startuml US09_CD
skinparam classAttributeIconSize 0

class VaccinationCenter {
  - name: String
  - address: String
  - emailAddress: String
  - phoneNumber: int
  - faxNumber: int
  - websiteAddress: String
  - openingHours: String
  - closingHours: String
  - slotDuration: int
  - maximumVaccinesPerSlot: int
  - coordinator: EMPLOYEE
  - typeId: int
  ---
 +VaccinationCenter(name,address,emailAddress,phoneNumber,faxNumber,websiteAddress,openingHours,closingHours,slotDuration,maximumVaccinesPerSlot,coordinator,typeId)
}


class Company {
  -designation: String
  ---
  +getDesignation()
  +getEmployeeStore()
  +getVaccinationCenterStore()
}

class VaccinationCenterStore {
---
+createVaccinationCenter(centerData,coordinator)
+validateVaccinatonCenter(center)
+saveVaccinationCenter(center)
+checkDuplicates(center)
-addVaccinationCenter(center)
}

class Employee {
  -id: String 
  -name: String 
  -email: String 
  -phone: String 
  -address: String 
  -citizenCardNumber: int 
  -roleId: String 
  ---
  +Employee(name,email,phone,address,citizenCardNumber,roleId)
}

class EmployeeStore {
  +getEmployeesWithRole(id)
}

class VaccinationCenterController {
  ---
  +getCoordinators()
  +createVaccinationCenter(name,address,emailAddress,phoneNumber,faxNumber,websiteAddress,openingHours,closingHours,slotDuration,maximumVaccinesPerSlot)
  +saveVaccinationCenter(center)
}

class VaccinationCenterUI {}

VaccinationCenterUI ..> VaccinationCenterController
VaccinationCenterController ..> Company
Company "1" --> "*" VaccinationCenter : belongs to <
Company ..> VaccinationCenterStore
Company ..> EmployeeStore
EmployeeStore "1" --> "*" Employee : stores >
Company "1" --> "*" Employee : knows >

@enduml