@startuml US09_CD
skinparam classAttributeIconSize 0

class VaccinationCenter {
  - name String
  - address String
  - emailAddress String
  - phoneNumber int
  - faxNumber int
  - websiteAddress String
  - openingHours String
  - closingHours String
  - slotDuration int
  - maximumVaccinesPerSlot int
  - coordinator EMPLOYEE
  ---
 +VaccinationCenter(name,address,emailAddress,phoneNumber,faxNumber,websiteAddress,openingHours,closingHours,slotDuration,maximumVaccinesPerSlot,coordinator)
}


class Company {
  -designation String
  ---
  +getDesignation()
  +createVaccinationCenter(name,address,emailAddress,phoneNumber,faxNumber,websiteAddress,openingHours,closingHours,slotDuration,maximumVaccinesPerSlot)
  +validateVaccinatonCenter(center)
  +saveVaccinationCenter(center)
  +getEmployeeByRoleId()
}

class VaccinationCenterStore {
---
+validateVaccinatonCenter()
+saveVaccinationCenter(center)
-addVaccinationCenter(center)
}

class Employee {
  -String id
  -String name
  -String email
  -String phone
  -String address
  -int citizenCardNumber
  -String roleId
  
  +Employee(name,email,phone,address,citizenCardNumber,roleId)
}

class EmployeeStore {
  +getEmployeesByRoleId()
  +getEmployeeById()
}

class VaccinationCenterController {
  ---
  +createVaccinationCenter(name,address,emailAddress,phoneNumber,faxNumber,websiteAddress,openingHours,closingHours,slotDuration,maximumVaccinesPerSlot)
  +saveVaccinationCenter(center)
}

class VaccinationCenterUI {}

VaccinationCenterUI ..> VaccinationCenterController
VaccinationCenterController ..> Company
Company "1" --> "*" VaccinationCenter : belongs to <
VaccinationCenterController ..> VaccinationCenter
Company ..> VaccinationCenterStore
Company ..> EmployeeStore
EmployeeStore "1" --> "*" Employee : stores

@enduml