@startuml US04_DM
hide methods
left to right direction
skinparam classAttributeIconSize 0

class Employee {
  - name
  - phoneNumber
  - email
  - password
  - address
  - citizenCardNumber
  - roleId
}

class Receptionist {}

class Arrival {
  - date
}

class Appointment {}

class SNSUser {
  - citizenCard
  - snsNumber
  - name
  - birthDay
  - gender
  - phoneNumber
  - email
  - address
}

class Company {
  - designation
}

class WaitingRoomList {}

Arrival "1" -- "0..1" Appointment : related to >
Company "1" -- "*" Employee : knows >
Employee -- Receptionist : plays as >
Company "1" -- "*" SNSUser : knows >
Receptionist "1" -- "*" Arrival : registers >
Receptionist "1" -- "*" WaitingRoomList : sends to >
SNSUser "*" -- "*" WaitingRoomList : is in >
SNSUser "1" -- "*" Arrival : associated to >

@enduml
