@startuml
hide methods
left to right direction
skinparam classAttributeIconSize 0


class Company {
  -designation
}

class Vaccine {
  -reference
  -designation
  -informalDesc
  -technicalDesc
  -duration
  -cost
}

class VaccineType {
  -id
  -description
}

class Administrator {
  -name
  -function
  -phone
  -email
}

class Administratoin process {
  -name
  -email
  -password
}




@enduml