@startuml
hide methods
left to right direction
skinparam classAttributeIconSize 0

class SNSUser {
  - citizenCard
  - snsNumber
  - name
  - birthDay
  - gender
  - phoneNumber
  - email
  - address
}

class Company {
  - designation
}

class Administrator {}

Administrator "1" -- "*" SNSUser : loads >
Company "1" -- "*" Administrator : knows >
Company "1" -- "*" SNSUser : knows >



@enduml