@startuml US09_SSD
autonumber
actor "Administrator" as Administrator

activate Administrator
Administrator -> ":System" : asks to create a new vaccination center
activate ":System"
":System" --> Administrator : requests data (name, address, phone number, e-mail address, fax number, website address, opening and closing hours, slot duration, maximum vaccines per slot)
deactivate ":System"

Administrator -> ":System" : types requested data
activate ":System"

":System" --> Administrator : shows all data and requests confirmation
deactivate ":System"

Administrator -> ":System" : confirms the data
activate ":System"
":System" -->Administrator : informs operation success
deactivate ":System"

deactivate Administrator

@enduml