@startuml
autonumber

actor "Receptionist" as RECEPT

participant ":RegisterSNSUserArrivalUI" as UI
participant ":RegisterSNSUserArrivalController" as CTRL
participant "comp:Company" as COMP
participant "suStore:SNSUserStore" as SUSTORE
participant "snsUser:SNSUser" as SNSUSER
participant "center:VaccinationCenter" as CENTER
participant "aptStore:AppointmentStore" as APTSTORE
participant "apt:Appointment" as APT
participant "arrival:Arrival" as ARRIVAL
participant "wrLst:WaitingRoomList" as WRLST

activate RECEPT
  RECEPT -> UI : starts to register the SNS User arrival to the vaccination center
  activate UI
  
  RECEPT <-- UI : asks for the SNS User number
  deactivate UI

  RECEPT -> UI : types the requested data
  activate UI
  
  RECEPT <-- UI : asks to select the vaccination center
  deactivate UI

  RECEPT -> UI : selects the vaccination center
  activate UI
    
    UI -> CTRL** : create(company)

    UI -> CTRL : findSNSUser(snsNumber)
    activate CTRL

      CTRL -> COMP : suStore = getSNSUserStore()
      activate COMP
      deactivate COMP

      CTRL -> SUSTORE : suStore.findSNSUser(snsNumber)
      activate SUSTORE
        loop for each snsUser
          SUSTORE -> SNSUSER : b = snsUser.hasSNSNumber(snsNumber)
          activate SNSUSER
          alt b == true
            SUSTORE <-- SNSUSER : return snsUser
            deactivate SNSUSER
          end
        end
      deactivate SUSTORE

    deactivate CTRL

    UI -> CTRL : findAppointment(snsNumber)
    activate CTRL

      CTRL -> CENTER : aptStore = getAppointmentStore()
      activate CENTER
      deactivate CENTER

      CTRL -> APTSTORE : apt = findAppointment(snsNumber)
      activate APTSTORE

        loop for each appointment
          APTSTORE -> APT : b = hasSNSNumber(snsNumber) && isInTheNextSlot()
          activate APT
          alt b == true
            APTSTORE <-- APT : return apt
            deactivate APT
          end
        end

      deactivate APTSTORE

    deactivate CTRL
  
  RECEPT <-- UI : asks for confirmation for the appointment
  deactivate UI

  RECEPT -> UI : confirms the data
  activate UI

    UI -> CTRL : confirmAppointment(apt)
    activate CTRL
      CTRL -> ARRIVAL** : create(snsUser, apt)

      CTRL -> WRLST : add(arrival)
      activate WRLST
      deactivate WRLST

    deactivate CTRL

  RECEPT <-- UI : informs operation success
  deactivate UI

deactivate RECEPT

@enduml