@startuml
autonumber

actor "Receptionist" as RECEPT

participant ":RegisterSNSUserArrivalUI" as UI
participant ":RegisterSNSUserArrivalController" as CTRL
participant "comp:Company" as COMP
participant "aptStore:AppointmentStore" as APTSTORE
participant "apt:Appointment" as APT
participant "wrLst:WaitingRoomList" as WRLST

activate RECEPT
  RECEPT -> UI : starts to register the SNS User arrival to the vaccination center
  activate UI
  
  RECEPT <-- UI : asks for the SNS User number
  deactivate UI

  RECEPT -> UI : types the requested data
  activate UI

    
    UI -> CTRL** : create(company)
    UI -> CTRL : findAppointment(snsNumber)
    activate CTRL

      CTRL -> COMP : aptStore = getAppointmentsStore()
      activate COMP
      deactivate COMP

      CTRL -> APTSTORE : apt = findAppointment(snsNumber)
      activate APTSTORE

        loop for each appointment
          APTSTORE -> APT : b = hasSNSNumber(snsNumber) && isInTheNextSlot()
          activate APT
          alt b == true
            APTSTORE <-- APT : return apt
            deactivate APT
          end
        end

      deactivate APTSTORE

    deactivate CTRL
  
  RECEPT <-- UI : asks for confirmation for the appointment
  deactivate UI

  RECEPT -> UI : confirms the data
  activate UI

    UI -> CTRL : confirmAppointment(apt)
    activate CTRL



    deactivate CTRL

  deactivate UI

deactivate RECEPT

@enduml