@startuml US08_SSD
autonumber
actor "Nurse" as nurse

activate nurse

nurse -> ":System" : asks to record the administration of a vaccine
activate ":System"
  ":System" --> nurse : requests data (snsNumber)
deactivate ":System"

nurse -> ":System" : types requested data
activate ":System"
  ":System" --> nurse : shows a list of all vaccines that have the vaccine type registered on the most recent arrival and asks to select one
deactivate ":System"

nurse -> ":System" : selects a vaccine
activate ":System"
  ":System" --> nurse : requests data (lotNumber, doseNumber)
deactivate ":System"

nurse -> ":System" : types requested data
activate ":System"
  ":System" --> nurse : shows all data and requests confirmation
deactivate ":System"

nurse -> ":System" : confirms the data
activate ":System"
  ":System" --> nurse : informs operation success
deactivate ":System"

@enduml