@startuml

hide methods
left to right direction
skinparam classAttributeIconSize 0

class CommunityMassVaccinationCenter {}

class HealthCareCenter {}

class VaccinationCenter {
  + name
  + address
  + phone
  + email
  + fax
  + website
  + openingHours
  + closingHours
  + slotDuration
  + nOfVaccinesPerSlot
}

class Vaccine {}

class VaccineType {
    + id
    + designation
    + whoid
}

class DGS {}

class SNSUser {}

class HealthInformation {}

class Administrator {}

class Employee {}

class Nurse {}

class Receptionist {}

class CenterCoordinator {}

class Appointment {
  + date
}

class AdministrationProccess {
  + ageGroup
  + dosage
  + nOfDoses
  + intervalBetweenDoses
}

class System {}

class AGES {}

class ARS {}

Vaccine "*" -- "1" VaccineType : has >

Employee <|-- Nurse
Employee <|-- Receptionist
Employee <|-- CenterCoordinator

VaccinationCenter <|-- CommunityMassVaccinationCenter
VaccinationCenter <|-- HealthCareCenter

VaccinationCenter "1" -- "1" CenterCoordinator : has >

HealthCareCenter "*" -- "1" AGES : belongs to > 
HealthCareCenter "*" -- "1" ARS : belongs to >

Appointment "1" -- "1" VaccinationCenter : is held in >
Appointment "1" -- "1" Vaccine : has a specefic >
Appointment "*" -- "1" Nurse : is assigned to <

Receptionist "1" -- "*" ReadyUsersList : manages >
Receptionist "1" -- "*" ArrivedUsersList : manages >

ReadyUsersList "1" -- "*" SNSUser : is composed by >
ArrivedUsersList "1" -- "*" SNSUser : is composed by > 
RecoveringUsersList "1" -- "*" SNSUser : is composed by >

ReadyUsersList "*" -- "1" Nurse : checks <
RecoveringUsersList "*" -- "1" Nurse : manages <

Administrator "1" -- "*" Employee : registers >
Administrator "1" -- "*" VaccinationCenter : registers >
Administrator "1" -- "*" VaccineType : manages >
Administrator "1" -- "*" Vaccine : manages >

VaccinationProcess -- DGS : manages <
VaccinationProcess -- SNSUser : is part of <

SNSUser "*" -- "1" Appointment : schedules >
SNSUser "1" -- "1" HealthInformation : has >

Vaccine "1" -- "*" AdministrationProccess : has >

System -- SMS : sends >
SNSUser -- SMS : receives <

@enduml
