@startuml UCD

left to right direction

actor "SNS User" as user
actor "Nurse" as nurse
actor "Receptionist" as recept
actor "Center Administrator" as cadmin
actor "DGS Administrator" as dgsadmin
actor "Center Coordinator" as coordinator
actor "DGS" as dgs

rectangle System {
  usecase "Schedule a vaccine" as UC01
  usecase "Request an EU COVID-19 digital certificate" as UC02
  usecase "Send a SMS with apointment details to SNS User" as UC03
  usecase "Issue a vaccination certificate" as UC04
  usecase "Schedule a vaccine to a SNS User" as UC05
  usecase "Check the list of SNS users that are present in the center to take the vaccine" as UC06
  usecase "Check user's health information" as UC07
  usecase "Report adverse reactions during recovery period" as UC08
  usecase "Register a SNS user vaccination details" as UC09
  usecase "Register the arrival of an SNS User" as UC10
  usecase "Register new vaccination centers" as UC11
  usecase "Register new SNS users" as UC12
  usecase "Register new center coordinators" as UC13
  usecase "Register new receptionists" as UC14
  usecase "Register new nurses" as UC15
  usecase "Monitor the vaccination process" as UC16
  usecase "View stats and charts" as UC17
  usecase "Generate a center report" as UC18
  usecase "Analyse from other centers" as UC19
  usecase "Configures vaccines" as UC20
  usecase "Manages vaccination centers" as UC21
  usecase "Manages employees" as UC22
}

user --> UC01
user --> UC02
dgs --> UC03
nurse --> UC04
nurse --> UC05
nurse --> UC06
nurse --> UC07
nurse --> UC08
nurse --> UC09
recept --> UC10
dgsadmin --> UC11
dgsadmin --> UC12
dgsadmin --> UC13
dgsadmin --> UC14
dgsadmin --> UC15
coordinator --> UC16
coordinator --> UC17
coordinator --> UC18
coordinator --> UC19
cadmin --> UC20
cadmin --> UC21
cadmin --> UC22


@enduml
