@startuml US09_SD
autonumber
actor "Administrator" as ADM

participant ":VaccinationCenterUI" as UI
participant ":VaccinationCenterController" as CTRL
participant "comp\n:Company" as COMP

activate ADM
ADM -> UI : asks to create a new vaccination center
activate UI
UI --> ADM : requests data (name,address,emailAddress,phoneNumber,faxNumber,websiteAddress,openingHours,closingHours,slotDuration,maximumVaccinesPerSlot)
deactivate UI

ADM -> UI : types requested data
activate UI

UI -> CTRL : coordinator=getEmployeeByRoleId()
activate CTRL

CTRL-> COMP : coordinator=getEmployeeByRoleId()
activate COMP

CTRL --> UI : list of coordinators
deactivate CTRL

UI --> ADM : shows all available center coordinators and asks to select one
deactivate UI
deactivate COMP

ADM -> UI : selects one center coordinator
activate UI

UI -> CTRL : center=createVaccinationCenter(name,address,emailAddress,phoneNumber,faxNumber,websiteAddress,openingHours,closingHours,slotDuration,maximumVaccinesPerSlot,coordinator)
activate CTRL

CTRL -> COMP : coordiantor=getEmployeeByRoleId(coodinatorId)
activate COMP
deactivate COMP

CTRL -> COMP: center=createVaccinationCenter(name,address,emailAddress,phoneNumber,faxNumber,websiteAddress,openingHours,closingHours,slotDuration,maximumVaccinesPerSlot,coordinator)
activate COMP
deactivate COMP

CTRL -> COMP: validateVaccinationCenter(center)
activate COMP

create "center\n:VaccinationCenter" as CENTER
COMP -> CENTER : create(name,address,phoneNumber,emailAddress,faxNumber,websiteAddress,openingAndClosingHours,slotDuration,maximumVaccinesPerSlot,coordinator)
deactivate COMP

CTRL --> UI : center created

UI --> ADM: shows all data and requests confirmation
deactivate COMP
deactivate CTRL
deactivate UI

ADM -> UI : confirms the vaccinationCenter data
activate UI
UI -> CTRL : saveVaccinationCenter(center)
activate CTRL

CTRL -> COMP : saveVaccinationCenter(center)
activate COMP

COMP -> COMP : validateVaccinationCenter(center)
COMP -> COMP : addVaccinationCenter(center)

CTRL --> UI : center validated and added to the data base

UI --> ADM : informs operation success
deactivate COMP
deactivate CTRL
deactivate UI

deactivate ADM

@enduml