@startuml US02_SSD
autonumber
actor "Receptionist" as Recept

activate Recept
Recept -> ":System" : asks to schedule a vaccination
activate ":System"
":System" --> Recept : requests data (SNSNumber, date, time)
deactivate ":System"
Recept -> ":System" : types requested data
activate ":System"

":System" --> Recept : shows all vaccination centers and asks to select one
deactivate ":System"
Recept -> ":System" : selects one vaccination center
activate ":System"

":System" --> Recept : shows all vaccine types and asks to select one
deactivate ":System"
Recept -> ":System" : selects one vaccine type
activate ":System"

":System" --> Recept : shows all data and requests confirmation
deactivate ":System"
Recept -> ":System" : confirms the data
activate ":System"
":System" --> Recept : informs operation success
deactivate ":System"

deactivate Recept

@enduml