@startuml US01_CD
skinparam classAttributeIconSize 0

class AppointmentUI {

}

class AppointmentController {

}

class Appointment {
  -SNSUser : SNSUser
  -vaccineType : VaccineType
  -vaccinationCenter : VaccinationCenter
  -date : Date
  -time : Time
  -sms : boolean
}

class AppointmentStore {

}

class Company {
  -designation : String
}

class VaccinationCenter {

}

class VaccinationCenterStore {

}

class VaccineType {

}

class VaccineTypeStore {

}

class Vaccine {

}

class VaccineStore {

}

class AdministeredVaccine {
  -appointment : Appointment
  -vaccine : Vaccine  
  -lotNumber : String
}

class AdministeredVaccineStore {

}

@enduml