@startuml US01_CD
skinparam classAttributeIconSize 0

class AppointmentUI {

}

class AppointmentController {
  +getSuggestedVaccineType()
  +getListOfVaccineTypes()
  +getListOfVaccinationCentersWithVaccineType(vaccineType)
  +createAppointment(appointmentDto)
  +saveAppointment()
}

class Appointment {
  -snsUser : SNSUser
  -vaccineType : VaccineType
  -vaccinationCenter : VaccinationCenter
  -date : Calendar
  -sms : boolean
  +getVaccinationCenter()
  +sendSMS()
}

class SMSSender {
  +sendSMS(phoneNumber, message)
}

class AppointmentStore {
  -appointments : List<Appointment>
  +createAppointment(appointmentDto)
  +checkDuplicateAppointment(snsUser, date)
  +saveAppointment(appointment)
  +validateAppointment(appointment)
  +addAppointment(appointment)
}

class Company {
  -designation : String
  +getSuggestedVaccineType()
  +getVaccineTypeStore()
  +getVaccinationCenterStore()
  +getAppointmentStore()
  +getUserSession()
  +getSNSUserStore()
}

class VaccinationCenter {
  -administeredVaccines : List<Vaccine>
  +getAdministeredVaccines()
  +checkAvailability(date, vaccineType)
  +addAppointmentToList(appointment)
}

class VaccinationCenterStore {
  -availableVaccinationCenters : List<VaccinationCenter>  
  +getVaccinationCentersByVaccineType(vaccineType)
}

class VaccineTypeStore {
  -vaccineTypes : List<VaccineType>
  +getVaccineTypes()
}

class Vaccine {
  -vaccineType : VaccineType
  +hasVaccineType(vaccineType)
}

class UserHealthData {
  +isEligibleForVaccine(vaccineType)
}

class SNSUser {
  -userHealthData : UserHealthData
  -snsNumber : String
  -phoneNumber : String
  +getSnsNumber()
  +getUserHealthData()
  +getPhoneNumber()
}

class SNSUserStore {
  -snsUsers : List<SNSUser>
  +findUserByEmail(email)
}

class UserSession {
  -userId : String
  +getUserId()
}

class VaccineType {

}

class VaccineTypeMapper {
  +toDto(vaccineTypes)
}

class VaccinationCenterMapper {
  +toDto(vaccinationCenters)
}

class AppointmentDto {
  -snsUser : SNSUser
  -vaccineType : VaccineType
  -vaccinationCenter : VaccinationCenter
  -date : Calendar
  +getVaccineType()
  +getVaccinationCenter()
  +getDate()
}

AppointmentUI ..> AppointmentController

AppointmentController ..> Company

Company ..> VaccineTypeStore
Company ..> VaccinationCenterStore
Company ..> AppointmentStore
Company ..> SNSUserStore
Company ..> UserSession

AppointmentStore "1" -- "*" Appointment : stores >

VaccinationCenterStore "1" -- "*" VaccinationCenter : stores >
VaccinationCenterStore ..> Vaccine

SNSUserStore "1" -- "*" SNSUser : stores >

VaccineTypeStore "1" -- "*" VaccineType : stores >

Appointment "*" -- "1" VaccinationCenter : is held at >
Appointment ..> SMSSender

VaccineType --o Vaccine
VaccineType --o Appointment

UserHealthData --o SNSUser

@enduml