@startuml US02_CD
skinparam classAttributeIconSize 0

class VaccinationSchedule {
  - date: Date
  - time: String
  +VaccinationSchedule(SNSUserNumber, date, time, center, vaccineType, sms)
}


class Company {
  -designation: String
  +getSNSUserStore()
  +getVaccinationCenterStore()
  +getVaccineTypeStore()
}

class VaccinationScheduleController {
  +createVaccinationSchedule(SNSUserNumber, date, time, center, vaccineType,sms)
}

class VaccinationScheduleUI {}

class SNSUserStore {
  + createUser(name, email, pwd, roleId)
  + validateUser(user)
  + saveUser(user)
  + checkDuplicates(user)
}

class VaccinationCenterStore {
+createVaccinationCenter(centerData,coordinator)
+validateVaccinatonCenter(center)
+saveVaccinationCenter(center)
+checkDuplicates(center)
-addVaccinationCenter(center)
}

class VaccineTypeStore {
  +getVaccineTypeByCode(code)
  +getList()
  +addVaccineType()
  +saveVaccineType()
}

class VaccinationCenter{
  - name: String
  - address: String
  - emailAddress: String
  - phoneNumber: String
  - faxNumber: String
  - websiteAddress: String
  - openingHours: String
  - closingHours: String
  - slotDuration: int
  - maximumVaccinesPerSlot: int
  +VaccinationCenter(name,address,emailAddres,phoneNumber,faxNumber,websiteAddress,openingHours,closingHours,slotDuration,maximumVaccinesPerSlot,coordinator)
}

class VaccineType {
  - code: String
  - description: String
  - technology: String
  + VaccineType(code,description,technology)
}

class SNSUser {
  - citizenCard: String 
  - snsNumber: String 
  - birthDay: Date 
  - gender: Char
  - phoneNumber: String 
  - address: String
  + SNSUser(citizenCard, snsNumber, name, birthDay, gender, phoneNumber, email, address)
  }

class Employee {
  -id: String 
  -name: String 
  -email: String 
  -phone: String 
  -address: String 
  -citizenCardNumber: int 
  -roleId: String 
  +Employee(name,email,phone,address,citizenCardNumber,roleId)
}

class Receptionist {}

class SMS {}

VaccinationScheduleUI ..> VaccinationScheduleController
VaccinationScheduleController ..> Company
Company ..> SNSUserStore
Company ..> VaccinationCenterStore
Company ..> VaccineTypeStore
Company "1" --> "*" Employee : knows
VaccinationCenterStore "1" -> "*" VaccinationCenter : stores
VaccineTypeStore "1" -> "*" VaccineType : stores
SNSUserStore "1" -> "*" SNSUser : stores
Employee "1" --> "1" Receptionist : play as
Employee ---o VaccinationCenter : coordinator
Receptionist "1" --> "1" VaccinationSchedule : is related to
VaccinationCenter "1" --o "*" VaccinationSchedule
SNSUser --o VaccinationSchedule
VaccineType "1" --o "1" VaccinationSchedule
SMS "0..1" --o "1" VaccinationSchedule : triggers SMS
VaccinationSchedule -- Appointment : creates new


@enduml