@startuml US02_CD
skinparam classAttributeIconSize 0

class Appointment {
  - date: Date
  - time: String
  +Appointment(SNSUserNumber, date, time, center, vaccineType, sms)
}

class AppointmentStore {}

class AppointmentUI {}

class AppointmentController {
  +createAppointment(SNSUserNumber, date, time, center, vaccineType,sms)
  +saveAppointment(appointment)
}

class Company {
  -designation: String
  +getSNSUserStore()
  +getVaccinationCenterStore()
  +getVaccineTypeStore()
  +getAppointmentStore()
}

class SNSUser {
  - citizenCard: String 
  - snsNumber: String 
  - birthDay: Date 
  - gender: Char
  - phoneNumber: String 
  - address: String
  + SNSUser(citizenCard, snsNumber, name, birthDay, gender, phoneNumber, email, address)
  }

class SNSUserStore {
  + createUser(name, email, pwd, roleId)
  + validateUser(user)
  + saveUser(user)
  + checkDuplicates(user)
}

class VaccinationCenter{
  - name: String
  - address: String
  - emailAddress: String
  - phoneNumber: String
  - faxNumber: String
  - websiteAddress: String
  - openingHours: String
  - closingHours: String
  - slotDuration: int
  - maximumVaccinesPerSlot: int
  +VaccinationCenter(name,address,emailAddres,phoneNumber,faxNumber,websiteAddress,openingHours,closingHours,slotDuration,maximumVaccinesPerSlot,coordinator)
}

class VaccinationCenterStore {
+createVaccinationCenter(centerData,coordinator)
+validateVaccinatonCenter(center)
-checkDuplicates(center)
+saveVaccinationCenter(center)
+size()
}

class VaccineType {
  - code: String
  - description: String
  - technology: String
  + VaccineType(code,description,technology)
}

class VaccineTypeStore {
  +getVaccineTypeByCode(code)
  +getList()
  +addVaccineType()
  +saveVaccineType()
}

class Employee {
  -id: String 
  -name: String 
  -email: String 
  -phone: String 
  -address: String 
  -citizenCardNumber: int 
  -roleId: String 
  +Employee(name,email,phone,address,citizenCardNumber,roleId)
}

class SMS {}

AppointmentUI ..> AppointmentController
AppointmentController ..> Company
Company ..> SNSUserStore
Company ..> VaccinationCenterStore
Company ..> VaccineTypeStore
Company ..> AppointmentStore
Company "1" --> "*" Employee : knows
VaccinationCenterStore "1" -> "*" VaccinationCenter : stores
VaccineTypeStore "1" -> "*" VaccineType : stores
SNSUserStore "1" -> "*" SNSUser : stores
Employee ---o VaccinationCenter : coordinator
VaccinationCenter "1" --o "*" Appointment
SNSUser "1" --o "*" Appointment
VaccineType "1" --o "1" Appointment
SMS "0..1" --o "1" Appointment : triggers SMS
AppointmentStore "1" -> "*" Appointment : stores


@enduml