@startuml US15_CD
skinparam classAttributeIconSize 0

package UI {
class ExportCenterStatisticsUI {}
}

package controllers {
     class ExportCenterStatisticsController {
       +createFullyVaccinatedData(filePath,startDate,endDate)
       +generateFullyVaccinatedUsersInterval()
       +saveData()
       +exportFileString()
       +getData()
       +createFullyVaccinatedData()
     }
}

   package utils {
     class Time {
       - hour: int
       - minute: int
       +Time(hour,minute)

       +Time(time)
     }
   }

package core {
  package domain {

    package service {

class FileUtils {
  +writeToFile()
  +hasNoExtension()
  +removeExtension()
  +removeSpecialChars()
  +buildDirStructure()
}
}

    package model {

class FullyVaccinatedData {
    +getVacAdminList()
    +getSnsUserAge()
    +getVaccine()
    +getVacType()
    }

class VaccineAdministration {
  -date: date
  +getSnsUserAge()
  +getVaccine()
  +getDose()
}

class VaccinationCenter {
    - name: String
    - emailAddress: String
    - phoneNumber: String
    - faxNumber: String
    - websiteAddress: String

    +VaccinationCenter(name,address,emailAddress,phoneNumber,faxNumber,websiteAddress,openingHours,closingHours,slot,coordinator)
}


class Employee {
    -id: String 
    -name: String 
    -email: String 
    -phone: String 
    -address: String 
    -citizenCardNumber: int 
    -roleId: String 

    +Employee(name,email,phone,address,citizenCardNumber,roleId)
}

class Slot {
    -duration: int
    -maxVaccinesPerSlot: int

    +Slot(duration,maxVaccinesPerSlot)
}

class Vaccine {
  -designation : String
  -brand : String
  -id : String
  -vacType : VaccineType

  +Vaccine(designation, id, brand, vacTypeId)
}

class VaccineType {
  -code
  -designation
  -technology 
}

class SNSUser {
  - citizenCard: String
  - snsNumber: String
  - name: String
  - birthDay: Calendar
  - gender: String
  - phoneNumber: String
  - email: String
  - address: String
  - userHealthData : UserHealthData
  + SNSUser(citizenCard, snsNumber, name, birthDay, gender, phoneNumber, email, address)
}

class Address {
  - street: String
  - doorNumber: String
  - postalCode: String
  - city: String
}


}

}


ExportCenterStatisticsUI ..> ExportCenterStatisticsController

VaccinationCenter o-- Employee : coordinator
VaccinationCenter o-- Time : openingHours
VaccinationCenter o-- Time : closingHours
VaccinationCenter o-- Slot
VaccinationCenter o-- Address : has <

Vaccine o-- VaccineType

Employee o-- Address : has <

VaccineAdministration -- Vaccine
VaccineAdministration -- SNSUser

FullyVaccinatedData -- VaccineAdministration : uses >

FileUtils <.. ExportCenterStatisticsController

ExportCenterStatisticsController ..> FullyVaccinatedData

@enduml