@startuml
skinparam classAttributeIconSize 0

package java{
    package util{
        class Timer{
            +scheduleAtFixedRate(task, firstTime, period)
        }
        abstract TimerTask{
            +TimerTask()
            +run()
            +cancel()
            +scheduleAtFixedRate(task, firstTime, period)
        }
    }


    package lang{
        interface Runnable{
            +run()
        }
    }
}
 
package core {
    

    package domain{
        package model{
            class Company{
                -designation: String
                -vaccinationCenterStore: VaccinationCenterStore
                -vaccineTypeStore: VaccineTypeStore
                +Company(designation)
                +scheduleExportDailyVaccinated(filePath, time, separator, timeInterval)
            }


            class ExportDailyVaccinatedTask {
                -filePath: String
                -vacCenterSt: VaccinationCenterStore
                -vacTypeSt: VaccineTypeStore
                -separator: char
                +ExportDailyVaccinatedTask(filePath, separator, vacCenterSt, vacTypeSt)
                +run()
            }
                    
            class VaccinationCenter {
                -name: String 
                -address: Address
                -phoneNumber: String
                -emailAddress: String
                -faxNumber: String
                -webSiteAddress: String
                +getVaccinaAdminList()
                +getName()
            }

            class Vaccine {
                -designation: String
                -brand: String
                -id: String
                -vacType: VaccineType
                -adminProcList: AdminProcList
                +getVacType()
            }

            class VaccineAdministration {
                -snsUser: SNSUser
                -vaccine: Vaccine
                -lotNumber: String
                -doseNumber: int
                -vaccinationCenter: VaccinationCenter
                -date: Calendar
                +getVaccine()
            }

            class VaccineType {
                -code: String
                -description: String
                -technology: String
                +getDescription()
            }
        }
        package stores{
            
            class VaccinationCenterStore {
                +getVaccinationCenters()
            }

            class VaccineTypeStore {
                +getVaccineTypes()
            }

        }
        package service{
            class FileUtils {
                +writeToFile(filepath, content)
            }
        }
    }
}


TimerTask ..|> Runnable
ExportDailyVaccinatedTask -|> TimerTask
ExportDailyVaccinatedTask --> FileUtils : uses
Company ..> VaccinationCenterStore : knows
Company ..> VaccineTypeStore : knows
Vaccine "*" o-- "1" VaccineType : has > 
VaccineAdministration "*" o-- "*" Vaccine : has >
VaccinationCenter "1" o-- "*" VaccineAdministration : has >
VaccineTypeStore "1" --> "*" VaccineType : store
VaccinationCenterStore "1" -> "*" VaccinationCenter : stores
Company --> Timer : uses
Timer --> ExportDailyVaccinatedTask : schedules

@enduml