@startuml

actor "Center Coordinator" AS COORD
participant ":AnalyseCenterPerformanceUI" as UI
participant ":AnalyseCenterPerformanceController" as CTRL

activate COORD
COORD -> UI : asks to list all present users in the waiting room for the vaccination the nurse is working on
activate UI
UI --> COORD : requests data (date & time interval)
COORD -> UI : types the requested data
UI --> COORD : the list with the differences of arrived and left users, maximum continuous sublist, its sum, the time inteval corresponding to this continuous sublist 
deactivate UI

deactivate COORD

@enduml
