@startuml
autonumber

actor "Center Coordinator" AS COORD
participant ":AnalyseCenterPerformanceUI" as UI
participant ":App" as APP

activate COORD
activate UI
UI -> APP : getInstance()
activate APP
deactivate APP
UI -> APP : company=getCompany()
activate APP
deactivate APP
create ":AnalyseCenterPerformanceController" as CTRL

UI --> CTRL : create(company,session)
deactivate UI
COORD -> UI : asks to list all present users in the waiting room for the vaccination the nurse is working on
activate UI
UI --> COORD : requests data (date & time interval)
deactivate UI
COORD -> UI : types the requested data


participant "employeeSession\n:EmployeeSession" as SESSION
participant "vaccinationCenter\n:VaccinationCenter" as VACC
participant "events\n:CenterEventList" as EVENTL
participant "centerPerformance\n:CenterPerformance" as PERF

activate UI
UI -> CTRL : analyseCenterPerformance()

activate CTRL
CTRL -> SESSION : center=getVaccinationCenter()
activate SESSION
deactivate SESSION
CTRL -> VACC : centerPerformance=getCenterPerformance(day,interval)
activate VACC
VACC -> VACC : events=getEventListForDay(day)
VACC -> VACC : centerPerformace=generatePerformanceReport(events,interval)
VACC --> CTRL : centerPerformance
|||
deactivate VACC
CTRL --> UI : centerPerformace
deactivate CTRL

UI --> COORD : the list with the differences of arrived and left users, maximum continuous sublist, its sum, the time inteval corresponding to this continuous sublist 
deactivate UI
deactivate COORD

@enduml
