@startuml US08_DM
hide methods
left to right direction
skinparam classAttributeIconSize 0

class Company {
  -designation
}

class CommunityMassVaccinationCenter {}

class HealthCareCenter {}

class VaccinationCenter {
  -name
  -address
  -emailAddress
  -phone
  -email
  -fax
  -website
}

class Vaccine {}

class VaccineType {
  -id
  -designation
  -whoId
}

class SNSUser {
  - citizenCard
  - snsNumber
  - name
  - birthDay
  - gender
  - phoneNumber
  - email
  - address
}

class Slot {
  -slotDuration
  -maxVacPerSlot
}

class Time {
  -openingHours
  -closingHours
}

class UserHealthData {}

class Employee {}

class Nurse {}

class AGES {}

class ARS {}

class Appointment {
  -snsUser
  -date
  -vaccinationCenter
  -vaccineType
  -sms
}

class Arrival {
  - arrivalDate
}

class VaccineAdministration {
  -snsUser
  -vaccine
  -lotNumber
  -doseNumber
  -vaccinationCenter
  -date
}

class Address {
  - street
  - doorNumber
  - postalCode
  - city
}

Arrival "1" -- "0..1" Appointment : related to >

Vaccine "*" -- "1" VaccineType : has <

Employee <|-- Nurse

Nurse "1" -- "*" UserHealthData : checks >
Nurse "1" -- "*" VaccineAdministration : registers >

VaccinationCenter <|-- CommunityMassVaccinationCenter
VaccinationCenter <|-- HealthCareCenter

VaccinationCenter "1" -- "1" Slot : has >
VaccinationCenter "1" -- "1" Time : has >

HealthCareCenter "*" -- "1" AGES : belongs to > 
HealthCareCenter "*" -- "1" ARS : belongs to > 

Employee "*" -- "1" Address : has >
VaccinationCenter "*" -- "1" Address : has >

Appointment "*" -- "1" VaccinationCenter : is held in >
Appointment "1" -- "1" VaccineType : has a specific >

SNSUser "1" -- "*" Appointment : schedules >
SNSUser "1" -- "*" Arrival : associated to >
SNSUser "1" -- "1" UserHealthData : has >

Company "1" -- "*" Employee : knows >
Company "1" -- "*" VaccinationCenter : knows >
Company "1" -- "*" SNSUser : knows >

VaccineAdministration "*" -- "1" Vaccine : has >
VaccineAdministration "*" -- "1" VaccinationCenter : is held in >

UserHealthData "1" -- "*" VaccineAdministration : has >