@startuml US10_CD
skinparam classAttributeIconSize 0

class Employee {
  -String name
  -String address
  -String phone number
  -String email
  -String citizen number
  -String password
  +Employee(name, address, phone number, email, citizen card number, password)
}

class Role {
  -String id
  -String description
  +Role(id,description)
  +getRoleById(id)
}

class Company {
  -String designation
  +Organization(designation)
  +getEmployeeRoles()
  +createEmployee(name, address, phone number, email, citizen card number, password, role)
  +validateEmployee(employee)
  +saveEmployee(employee)
  -addEmployee(employee)
}

class CreateEmployeeController {
  +getEmployeeRoles()
  +createEmployee(name, address, phone number, email, citizen card number, password, roleId)
  +saveEmployee()
}

class CreateEmployeeUI {
}

CreateEmployeeUI ..> CreateEmployeeController
CreateEmployeeController ..> Employee
CreateEmployeeController ..> Company
Company ..> Employee
Employee "*" --* "1" Role

@enduml