@startuml US10_CD
skinparam classAttributeIconSize 0

class Employee {
  -String address
  -String citizen number
  +Employee(name, address, phone number, email, citizen card number, password, role)
}

interface User {  
  -String name
  -String phone number
  -String email
  -String password
  -String role
  +User(name, phone number, email, password, role)
}

class Company {
  -String designation
  +Organization(designation)
  +getEmployeeRoles()
  +createEmployee(name, address, phone number, email, citizen card number, password, role)
  +validateEmployee(employee)
  +saveEmployee(employee)
  +getRoleById(id)
  -addEmployee(employee)
}

class CreateEmployeeController {
  +getEmployeeRoles()
  +createEmployee(name, address, phone number, email, citizen card number, password, roleId)
  +saveEmployee()
}

class CreateEmployeeUI {
}

CreateEmployeeUI ..> CreateEmployeeController
CreateEmployeeController ..> Employee
CreateEmployeeController ..> Company
Company ..> Employee
User <|.. Employee 

@enduml