@startuml US04_SSD
autonumber
actor "Receptionist" as RECEPT

activate RECEPT
RECEPT -> ":System" : wants to register a user arrival

activate ":System"
":System" --> RECEPT : asks for the SNS User number
deactivate ":System"

RECEPT -> ":System" : types the SNS User number

alt there is an appointment
  activate ":System"
  ":System" --> RECEPT : 
  deactivate ":System"
end

alt there is not an appointment
  activate ":System"
  ":System" --> RECEPT : 
  deactivate ":System"
end

deactivate RECEPT

@enduml