@startuml
autonumber
actor "Administrator" as Admin

activate Admin
Admin -> ":System" : asks to create a new vaccine type
activate ":System"
":System" --> Admin : requests data (...)
deactivate ":System"

Admin -> ":System" : types requested data
activate ":System"
":System" --> Admin : shows all data and requests confirmation
deactivate ":System"

Admin -> ":System" : confirms the data
activate ":System"
":System" --> Admin : informs operation success
deactivate ":System"

deactivate Admin

@enduml
