@startuml
autonumber
'hide footbox
actor "Timer" as ACTOR

participant "App" as APP
participant "Company" as COMP
participant "task: ExportDailyVaccinatedTask" as TASK
participant "timer: Timer" as TIMER



APP -> APP : StartUp()
activate APP
    APP -> COMP : scheduleExportDVac()
    activate COMP
deactivate APP

        note right of COMP
            aqui recebe isto??? recebe tambem as stores necessarias??
        end note 
        COMP -> TASK ** : create(filePath)

        COMP -> TIMER ** : create()

        COMP -> TIMER : schedule(task, dateTime)
        activate TIMER
        deactivate TIMER

        note right of COMP
            After the time to the specifiede date and time has elapsed
        end note 
        
    deactivate COMP

        TIMER -> TASK : run()
        activate TIMER
        deactivate TIMER
        activate TASK
        deactivate TASK




@enduml 