@startuml
hide methods
left to right direction
skinparam classAttributeIconSize 0

class Company {
  -designation
}

class Vaccine {
  -designation
}

class VaccineType {
  - code
  - designation
  - whoid
}

class Administrator {
}

class Administratoin Process {
  - Age group maximum limit
  - Age group minimum limit
  - Number of doses
}

class Doses Information {
  - dose number
  - dosage
  - time interval to next dose
}

Company "1" -- "*" Vaccine : knows
Company "1" -- "*" VaccineType : knows


@enduml