@startuml Sequence Diagram
autonumber
'hide footbox
actor "Receptionist" as RECEPT

participant ":RegisterSNSUserUI" as UI
participant ":RegisterSNSUserController" as CTRL
' participant "app\n:ApplicationPOT" as APP
' participant ":Platform" as PLAT
participant "comp\n:Company" as COMP
participant "auth\n:AuthFacade" as AUTH

activate RECEPT
RECEPT -> UI : starts to register a new SNS User
activate UI
UI --> RECEPT : requests data (SNSNumber, name, birthDate, sex, phoneNumber, email)
deactivate UI

RECEPT -> UI : types requested data
activate UI

UI --> CTRL : createUser(userData)
activate CTRL

activate COMP
CTRL --> COMP : user = createUser(userData)
deactivate UI





deactivate RECEPT

@enduml