@startuml
autonumber
'hide footbox
actor "Receptionist" as RECEPT

participant ":RegisterSNSUserUI" as UI
participant ":RegisterSNSUserController" as CTRL
participant "app\n:ApplicationPOT" as APP
' participant ":Platform" as PLAT
participant "comp\n:Company" as COMP

activate RECEPT
RECEPT -> UI : asks to register a new SNS User
activate UI
UI --> RECEPT : requests the data (SNSNumber, name, birthDate, phoneNumber, email)
deactivate UI

RECEPT -> UI : types requested data
activate UI

activate CTRL
UI --> CTRL : snsUser = addNewSNSUser()
activate APP
CTRL --> APP : snsUser = addNewSNSUser()
deactivate UI





deactivate RECEPT

@enduml