@startuml Sequence Diagram
autonumber
'hide footbox
actor "Receptionist" as RECEPT

participant ":RegisterSNSUserUI" as UI
participant ":RegisterSNSUserController" as CTRL
' participant "app\n:ApplicationPOT" as APP
' participant ":Platform" as PLAT
participant "comp\n:Company" as COMP
participant "user\n:User" as USER
participant "auth\n:AuthFacade" as AUTH
participant "lstSnsU\n:List<SNSUser>" as LIST

activate RECEPT
RECEPT -> UI : starts to register a new SNS User
activate UI
UI --> RECEPT : requests data (SNSNumber, name, birthDate, sex, phoneNumber, email)
deactivate UI

RECEPT -> UI : types requested data
activate UI

UI --> CTRL : createUser(userData)
activate CTRL

CTRL --> COMP : user = createUser(userData)
activate COMP
deactivate COMP

CTRL --> COMP : validateUser(user)
activate COMP

COMP --> USER : email = getEmail(user)
activate USER
deactivate USER

COMP --> AUTH : existsUser(email)
activate AUTH
deactivate AUTH

COMP --> COMP : checkDuplicates(user)
activate COMP
deactivate COMP

deactivate COMP
deactivate CTRL

UI --> RECEPT : shows data and asks for confirmation
deactivate UI

RECEPT --> UI : confirms the data
activate UI

UI --> CTRL : saveUser(user)
activate CTRL

CTRL --> COMP : validateUser(user)
activate COMP
deactivate COMP

CTRL --> USER : saveUser(user)
activate USER

USER --> LIST : add(user)
activate LIST
deactivate LIST

deactivate USER

deactivate CTRL

UI --> RECEPT : informs operation success
deactivate UI

deactivate RECEPT

@enduml