@startuml US01_DM
hide methods
skinparam classAttributeIconSize 0

class Appointment {}

class VaccineType {}

class SNSUser {
  -citizenCard
  -snsNumber
  -name
  -birthDay
  -gender
  -phoneNumber
  -email
  -address
}

class VaccinationCenter{
  -name
  -address
  -emailAddress
  -phoneNumber
  -faxNumber
  -websiteAddress
  -openingHours  
  -closingHours
  -slotDuration
  -maximumVaccinesPerSlot
  -coordinator
}

class Company {
  -designation
}

Appointment "1"  -- "1" VaccineType : has >
Appointment "*" -- "1" VaccinationCenter : is held at >

Company "1" -- "*" VaccinationCenter : knows >

SNSUser "1" -- "*" Appointment : schedules >

@enduml