@startuml US17_SSD_1
autonumber

actor "Center Coordinator" as COORDINATOR

activate COORDINATOR

COORDINATOR -> ":System" : starts the process of importing data from a legacy system
activate ":System"

":System" --> COORDINATOR : asks for the file path that should be loaded
deactivate ":System"

COORDINATOR -> ":System" : inserts the file path
activate ":System"

' sorted by arrival time or by the center leaving time
":System" --> COORDINATOR : opens the file and shows data sorted
deactivate ":System"

COORDINATOR -> ":System" : confirms the data
activate ":System"

":System" --> COORDINATOR : informs operation success
deactivate ":System"

deactivate COORDINATOR

@enduml
