@startuml
hide methods
skinparam classAttributeIconSize 0

class Administrator {}

class Employee {
}

class Company {
  - designation
}

Administrator "1" -- "*" Employee : lists 

Company "1" -- "*" Administrator : knows  >
Company "1" -- "*" Employee : knows >

Employee <|-- Nurse
Employee <|-- Receptionist
Employee <|-- CenterCoordinator

@enduml
