@startuml
autonumber
'hide footbox
actor "Administrator" as ADM

participant ":ListEmployeeUI" as UI
participant ":ListEmployeeController" as CTRL
participant "comp\n:Company" as COMP
participant "lsEmp:List<Employee>" as LST
participant "emp:Employee" as EMP

activate ADM
ADM -> UI : asks to list employees for given role
activate UI
activate CTRL
UI -> CTRL : roleList=getEmployeeRoles()

CTRL -> COMP : roleList=getEmployeeRoles()
activate COMP
|||
deactivate COMP
deactivate CTRL

UI --> ADM : shows roles list and ask to select one
deactivate UI

ADM -> UI : selects an employee role
activate UI

UI -> CTRL : role=getEmployeeRoleById(roleId)
activate CTRL

activate COMP
CTRL -> COMP: employees=getEmployeesByRoleId(roleId)
COMP --> LST

loop for each employee
  activate EMP
    COMP -> EMP: e=hasRole(roleId)
    EMP --> COMP: true/false
    alt e==true
        COMP -> LST: add(employee)
      activate LST
      deactivate LST
    end
  deactivate EMP
end

LST --> CTRL: lsEmp
CTRL --> UI: lsEmp

deactivate COMP
deactivate CTRL
UI --> ADM : informs operation success
UI --> ADM: shows the list of employees
deactivate UI

deactivate UI
deactivate CTRL
deactivate ADM

@enduml
