@startuml
autonumber
'hide footbox
actor "Administrator" as ADM

participant ":ListEmployeeUI" as UI
participant ":ListEmployeeController" as CTRL
participant "comp\n:Company" as COMP
participant "employeeStore\n:EmployeeStore" as EMPS
participant "authFacade\n:AuthFacade" as AUTH
participant "emp:Employee" as EMP


activate ADM
ADM -> UI : asks to list employees for given role
activate UI
activate CTRL
UI -> CTRL : roleList=getEmployeeRoles()
CTRL -> COMP : authFacade=getAuthFacade()
activate COMP
deactivate COMP

CTRL -> AUTH : roleList=getUserRoles()
activate AUTH
|||
deactivate AUTH
deactivate CTRL

UI --> ADM : shows roles list and ask to select one
deactivate UI

ADM -> UI : selects an employee role
activate UI

UI -> CTRL : getEmployeesByRoleId(roleId)
activate CTRL

CTRL -> COMP: getEmployeeStore()
activate COMP
deactivate COMP
CTRL -> EMPS: getEmployeesByRoleId(roleId)
activate EMPS
deactivate EMPS
EMPS -> AUTH: existsRole(roleId)
activate AUTH
deactivate AUTH
create "lstEmp\n:List<Employee>" as LST
EMPS --> LST

loop for each employee
    EMPS -> EMP: e=employee.roleId == roleId
  activate EMP
    EMP --> EMPS: true/false
  deactivate EMP
    alt e==true
        EMPS -> LST: add(employee)
      activate LST
    |||
    deactivate LST
    end
end

CTRL --> UI: lstEmp

deactivate COMP
deactivate CTRL
UI --> ADM : informs operation success
UI --> ADM: shows the list of employees
deactivate UI

deactivate UI
deactivate CTRL
deactivate ADM

participant "roleList:\nList<UserRole>"

@enduml
