@startuml
autonumber
'hide footbox
actor "Administrator" as ADM

participant ":ListEmployeeUI" as UI
participant ":ListEmployeeController" as CTRL
participant "role\n:Role" as ROLE
participant "comp\n:Company" as COMP

activate ADM
ADM -> UI : asks to list employees for given role
activate UI
UI --> ADM : shows roles list and ask to select one
activate CTRL
UI -> CTRL : roleList=getEmployeeRoles()
deactivate UI

CTRL -> COMP : roleList=getEmployeeRoles()
activate COMP
|||
deactivate COMP
deactivate CTRL

ADM -> UI : selects an employee role
activate UI

UI -> CTRL : role=getEmployeeRoleById(roleId)
activate CTRL

CTRL -> ROLE: role=getRoleById(roleId)
activate ROLE

ROLE --> ROLE: validate(roleId)
activate COMP
deactivate ROLE
CTRL --> COMP: employees=getEmployeesByRole(roleId)

CTRL --> UI: result

deactivate COMP
deactivate CTRL
UI --> ADM : informs operation success
UI --> ADM: shows the list of employees
deactivate UI


deactivate UI
deactivate CTRL
deactivate ADM

@enduml
