@startuml
skinparam classAttributeIconSize 0

class User {
  - String name
  - String email
  - String pwd
  - String roleId
}

class Employee {
  +Employee(name,email,pwd,roleId)
}

class Company {
  -String designation
  +Company(designation)

  +getEmployeesByRoleId(roleId)
}

class ListEmployeeController {
  +getRoles()
  +getEmployeesByRoleId(role)
}

class ListEmployeeUI {}

ListEmployeeUI ..> ListEmployeeController
ListEmployeeController ..> Employee
ListEmployeeController ..> Company
Company "1" --> "*" Employee : employees

User <|.. Employee 

@enduml
