@startuml
skinparam classAttributeIconSize 0

hide RoleId methods

interface User {
  - String name
  - String email
  - String pwd
  - String roleId
}

class Employee {
  +Employee(name,email,pwd,roleId)
}

class Company {
  -String designation
  +Company(designation)

  +getEmployeesByRoleId(roleId)
}

class ListEmployeeController {
  +getRoles()
  +getEmployeesByRoleId(role)
}

class ListEmployeeUI {}

enum RoleId {
  NURSE
  RECEPTIONIST
  CENTER_COORDINATOR
  ADMINISTRATOR
  SNS_USER
}

ListEmployeeUI ..> ListEmployeeController
ListEmployeeController ..> Employee
ListEmployeeController ..> Company

Company "1" --> "*" Employee : employees

User <|.. Employee 

@enduml
