@startuml
skinparam classAttributeIconSize 0

class User {
  - String name
  - String email
  - String pwd
  - String roleId
}

class Employee {
  -String id
  -String name
  -String email
  -String phone
  -String address
  -int citizenCardNumber
  -String roleId
  
  +Employee(name,email,phone,address,citizenCardNumber,roleId)
}

class Company {
  -String designation
  +Company(designation)

  +getAuthFacade()
}

class AuthFacade {
  +existsRole(role)
  +getUserRoles()
  +getUsersWithRole(roleId)
}

class EmployeeStore {
  +getEmployeesWithRole(roleId)
}

class ListEmployeeController {
  +getRoles()
  +getEmployeesByRoleId(role)
}

class UserRole {
  -String id
  -String description
}

class UserRolesStore {

}

class ListEmployeeUI {}

ListEmployeeUI ..> ListEmployeeController
ListEmployeeController ..> Employee
ListEmployeeController ..> Company

Company ..> AuthFacade
Company ..> EmployeeStore
EmployeeStore -> AuthFacade : uses
Employee "*" -- "1" EmployeeStore : stores <
Company "1" --> "*" Employee : knows >

UserRolesStore "1" -- "*" UserRole : stores >
AuthFacade ..> UserRolesStore
User "1" -- "*" UserRole : has >

User <|-- Employee 

@enduml
