@startuml US10_DM
hide methods
skinparam classAttributeIconSize 0

class Company {
  -designation
}

class Administrator {
}

class Employee {
  -name
  -phone number
  -email
  -password
  -address
  -citizen card number
  -role
}

Company "1" -- "*" Administrator : knows >
Company "1" -- "*" Employee : knows >
Administrator "1" -- "*" Employee : registers >

@enduml