@startuml US10_DM
hide methods
skinparam classAttributeIconSize 0

class Company {
  -designation
}

class Administrator {
}

class Receptionist {  
}

class Nurse {
}

class CenterCoordinator {
}

class Employee {
  -name
  -address
  -phone number
  -email
  -citizen card number
}

Company "1" -- "*" Administrator : knows >
Company "1" -- "*" Employee : knows >
Administrator "1" -- "*" Employee : registers >
Employee <|-- Receptionist
Employee <|-- Nurse
Employee <|-- CenterCoordinator

@enduml