@startuml US10_DM
hide methods
skinparam classAttributeIconSize 0

class Company {
  -designation
}

class Administrator {
}

class Role {
  -id
  -description
}

class Employee {
  -name
  -address
  -phone number
  -email
  -citizen card number
}

Company "1" -- "*" Administrator : knows >
Company "1" -- "*" Role : knows >
Company "1" -- "*" Employee : knows >
Administrator "1" -- "*" Employee : registers >
Employee "*" -- "1" Role : has >

@enduml