@startuml SD_VaccinationCenter_toDto_List

participant "vaccinationCenterStore\n:VaccinationCenterStore" as CENTERSTORE
participant "vaccineTypeMapper\n:VaccineTypeMapper" as VACCINEMAPPER
participant "vaccinationCenter\n:VaccinationCenter" as CENTER
participant "vaccinationCenterMapper\n:VaccinationCenterMapper" as CENTERMAPPER
participant "availableVaccinationCentersList\n:List<VaccinationCenter>" as CENTERLIST
participant "vaccinationCenterDtoList\n:List<VaccinationCenterDto>" as CENTERDTOLIST
participant "communityMassVaccinationCenter\n:CommunityMassVaccinationCenter"
participant "healthCareCenter\n:HealthCareCenter" 

[o-> CENTERSTORE : getListOfVaccinationCentersWithVaccineType(vaccineTypeDto)
activate CENTERSTORE

CENTERSTORE -> CENTERLIST** : create()

CENTERSTORE -> VACCINEMAPPER : vaccineType = toModel(vaccineTypeDto)
activate VACCINEMAPPER
deactivate VACCINEMAPPER

loop for each VaccinationCenter registered in the system
opt vaccinationCenter instanceof CMVC

CENTERSTORE -> CENTER : a = administersVaccineType(vaccineType)
activate CENTER 
deactivate CENTER

opt a==true
CENTERSTORE -> CENTERLIST : add(vaccinationCenter)
activate CENTERLIST
deactivate CENTERLIST
deactivate CENTER
end

alt vaccinationCenter instanceof HCC
CENTERSTORE -> CENTERLIST : add(vaccinationCenter)
activate CENTERLIST
deactivate CENTERLIST
deactivate CENTER
end
end
end

CENTERSTORE -> CENTERMAPPER : availableVaccinationCentersDto = toDto(availableVaccinationCenters)
activate CENTERMAPPER
deactivate CENTERMAPPER

[<-CENTERSTORE : vaccinationCenterDtoList
deactivate CENTERSTORE

@enduml