@startuml US02_SD
autonumber
'hide footbox
actor "Receptionist" as RECEPT

participant ":VaccinationScheduleUI" as UI
participant ":VaccinationScheduleController" as CTRL
participant "comp\n:Company" as COMP
participant "dto:VaccinationScheduleDto" as DTO

activate RECEPT
RECEPT -> UI : asks to schedule a vaccination
activate UI
UI --> RECEPT : requests data (SNSUserNumber, date, time)
deactivate UI

RECEPT -> UI : types requested data
activate UI

deactivate RECEPT

@enduml