@startuml
skinparam classAttributeIconSize 0

class AuthFacade {
  + existsUser(email)
  + addUserWithRole(name, email, pwd, roleId)
}

class Company {
  - String designation
  + getSNSUserStore()
  + getAuthFacade()
}

class UploadUsersFromFileController {
  + createCsvReader()
  + readAndUpload()
}

class UploadUsersFromFileUI { }

class SNSUser {
  - String citizenCard
  - String snsNumber
  - Date birthDay
  - Char gender
  - String phoneNumber
  - String address
}

class SNSUserStore {
  + createSNSUser(name, email, pwd, roleId)
  + validateSNSUser(snsUser)
  + saveSNSUser(snsUser)
  + checkDuplicates(snsUser)
  + registListOfUsers(userDataList)
  + addSNSUser(snsUser)
}

class PasswordGenerator {
  + generatePassword()
}

class EmailSender {
  + sendEmail(email)
}

class CSVReader {
  - String filePathName

  + readSNSUsersData()
  + validatePath()
  + validateFile()
  + getFileSeparator()
}

class UserMapper{
  + toDto(snsUser)
}

class UserDto{
  + name
  + email
  + password 
  + roleId
}

Company ..> SNSUserStore
Company ..> AuthFacade
Company "1" --> "*" SNSUser : knows
UploadUsersFromFileController ..> Company
UploadUsersFromFileUI ..> UploadUsersFromFileController
UploadUsersFromFileController --> CSVReader : uses
SNSUserStore --> AuthFacade : uses
SNSUserStore --> PasswordGenerator : uses
SNSUserStore --> EmailSender : uses
SNSUserStore ..> SNSUser
SNSUserStore --> UserMapper : user
UserMapper --> UserDto : converts to


@enduml