@startuml Domain Model

hide methods
left to right direction
skinparam classAttributeIconSize 0

class CommunityMassVaccinationCenter {}

class HealthCareCenter {}

class VaccinationCenter {
  name
  address
  phone
  email
  fax
  website
  openingHours
  closingHours
  slotDuration
  nOfVaccinesPerSlot
}

class Vaccine {}

class VaccineType {
  id
  designation
  whoid
}

class SNSUser {}

class HealthInformation {}

class Administrator {}

class Employee {}

class Nurse {}

class Receptionist {}

class CenterCoordinator {}

class Appointment {
  date
  doseNumber
}

class AdministrationProccess {
  ageGroup
  nOfDoses
}

class AGES {}

class ARS {}

class IntervalBetweenDoses {
  dosage
  timeToNextDose
  doseNumber
}

IntervalBetweenDoses "1" -- "1" AdministrationProccess : has <

Vaccine "*" -- "1" VaccineType : has <

Employee <|-- Nurse
Employee <|-- Receptionist
Employee <|-- CenterCoordinator

VaccinationCenter <|-- CommunityMassVaccinationCenter
VaccinationCenter <|-- HealthCareCenter

VaccinationCenter "1" -- "1" CenterCoordinator : has < 

HealthCareCenter "*" -- "1" AGES : belongs to > 
HealthCareCenter "*" -- "1" ARS : belongs to > 

Appointment "*" -- "1" VaccinationCenter : is held in >
Appointment "1" -- "1" Vaccine : has a specefic >
Appointment "1" -- "1" Notification : triggers >

Receptionist "1" -- "*" ReadyUsersList : manages >
Receptionist "1" -- "*" ArrivedUsersList : manages >

ReadyUsersList "1" -- "*" SNSUser : is composed by >
ArrivedUsersList "1" -- "*" SNSUser : is composed by > 
RecoveringUsersList "1" -- "*" SNSUser : is composed by >

ReadyUsersList "*" -- "1" Nurse : checks <
RecoveringUsersList "*" -- "1" Nurse : manages <

Administrator "1" -- "*" Employee : registers >
Administrator "1" -- "*" VaccinationCenter : registers >
Administrator "1" -- "*" VaccineType : manages >
Administrator "1" -- "*" Vaccine : manages > 

SNSUser "1" -- "*" Appointment : schedules >
SNSUser "1" -- "1" HealthInformation : has >

Vaccine "1" -- "1..*" AdministrationProccess : has >

SNSUser "1" -- "*" Notification : receives >

SNSUser "1" -- "*" VaccinationCertificate : requests >

VaccinationCertificate "1" -- "1" Vaccine : corresponds >
Company "1" -- "*" VaccinationCertificate : emmits >

Receptionist "0,1" -- "1" Appointment : schedules >

Nurse "1" -- "*" AdverseReaction : reports >
Nurse "1" -- "*" HealthInformation : checks >

VaccinationCenter "1" -- "1" VaccinationReport : has >
CenterCoordinator "1" -- "*" VaccinationReport : analyses >
CenterCoordinator "1" -- "*" VaccinationReport : generates >

Nurse "1" -- "*" AdministrationProccess : checks >

Notification <|-- SMS
Notification <|-- Email

AdverseReaction "*" -- "1" Appointment : has <

@enduml
