@startuml
autonumber
actor "Nurse" as NURSE

activate NURSE
NURSE -> ":System" : asks to list all present users in the waiting room of a given vaccination center
activate ":System"
":System" --> NURSE : shows all vaccination centers and asks to select one
deactivate ":System"

NURSE -> ":System" : selects a vaccination center
activate ":System"
":System" --> NURSE : lists all the users present on the waiting room
deactivate ":System"

deactivate NURSE

@enduml
