@startuml
autonumber
actor "Nurse" as NURSE

activate NURSE
NURSE -> ":System" : asks to list all present users in the waiting room for the vaccination he/she is working on
activate ":System"
":System" --> NURSE : lists all the users present on the waiting room
deactivate ":System"

deactivate NURSE

@enduml
