@startuml US15_SD

actor "Center Coordinator" as COORDINATOR

participant ":ExportCenterStatisticsUI" as UI
participant ":App" as APP
participant ":ExportCenterStatisticsController" as CTRL
participant ":Company" as COMP
participant "exportercsv\n:ExporterCsvData" as EXPORTER
participant "vaccineAdministration\n:VaccineAdministration" as VACADMIN
participant "userhealthdata\n:UserHealthData" as USERDATA
participant "vaccinationCenter\n:VaccinationCenter" as CENTER


activate COORDINATOR
COORDINATOR -> UI : asks to export center statistics
activate UI

UI -> APP : comp = app.getCompany()
activate APP
deactivate APP

ref over UI 
**center** is obtained through the coordinatorSession
See here: CoordinatorLogin_SD.svg
end ref
UI --> CTRL** : create(company,center)

UI --> COORDINATOR : requests data (file path name)
deactivate UI

COORDINATOR -> UI : types requested data
activate UI

UI -> CTRL : createCsvExporter(filePathName)
activate CTRL

CTRL --> EXPORTER** : exporterCsv = create(filePathName)

loop 
EXPORTER -> VACADMIN :  snsUserAge = getSNSUserAge()
activate EXPORTER
activate VACADMIN
deactivate VACADMIN

EXPORTER -> VACADMIN : vaccine = getVaccine()
activate VACADMIN
deactivate VACADMIN

EXPORTER -> VACADMIN : adminProcByAge = vaccine.getAdminProc()
activate VACADMIN
deactivate VACADMIN

EXPORTER -> VACADMIN : dose = getDose()
activate VACADMIN
deactivate VACADMIN

EXPORTER -> VACADMIN : date = getDate()
activate VACADMIN
deactivate VACADMIN

EXPORTER -> EXPORTER : vacType = vaccine.getVacType()
activate EXPORTER
deactivate EXPORTER
 
opt  doseInfo.size() == dose then snsUser is fully vaccinated 
EXPORTER -> EXPORTER : info.put(vacType)
end

deactivate EXPORTER
deactivate CTRL
end

UI --> COORDINATOR : informs operation success

deactivate COORDINATOR 

@enduml