@startuml
skinparam classAttributeIconSize 0

class CreateVaccineUI{

}

class CreateVaccineController{
    +getVacTypes()
    +getVaccines()
    +createVaccine(designation, numberAgeGroups, vacTypeId)
    +createAdminProc(minAge, maxAge, numberOfDoses)
    +saveAdminProc()
    +createDoseInfo(dosage, timaToNextDose)
    +safeDoseInfo
    +saveVaccine()
}

class Company{
    -designation : String

    +getVaccineTypeStore()
    +getVaccineStore()
}

class VaccineTypeStore{
    +getVacTypeId(vacTypeId)
}

class VaccineStore{
    +createVaccine(designation, numberAgeGroups, vacType)
    +validateVaccine(vac)
}

class Vaccine{
    -designation : String
    -numberOfAgeGroups : int
    -brand : String

    +create(designation, numberAgeGroups, vacType)
    +createAdminProc(minAge, maxAge, numberOfDoses)
    +validateAdminProc(adminProc)
}

class VaccineType{
    -code : int
    -description : String
    -tecnhology : String
}

class AdminProc{
    -numberOfDoses : int
    -minAge : int
    -maxAge : int

    +create(minAge, maxAge, numberOfDoses)
    +createDoseInfo(dosage, timeSinceLastDose)
    +validateDoseInfo(doseInfo)
}

class AdminProcList{
    +addAdminProc(adminProc)
}

class DoseInfo{
    -dosage : int
    -timeToNextDose : int

    +creat(dosage, timeToNextDose)
}

class DoseInfoList{
    +addDoseInfo(doseInfo)
}

CreateVaccineUI ..> CreateVaccineController
CreateVaccineController ..> VaccineStore
CreateVaccineController ..> VaccineTypeStore
CreateVaccineController ..> Company
VaccineStore ..> Company
VaccineStore "1" -> "*" Vaccine : stores
VaccineTypeStore ..> Company
VaccineTypeStore "1" -> "*" VaccineType : stores
Company "1" -> "*" Vaccine : knows
Vaccine "1" -> "1" AdminProcList : has
Vaccine "1" -> "1" VaccineType : has
AdminProcList "1" -> "*" AdminProc : has
AdminProc "1" -> "1" DoseInfoList : has
DoseInfoList "1" -> "*" DoseInfo : has

@enduml