@startuml
skinparam classAttributeIconSize 0

class CreateVaccineUI{

}

class CreateVaccineController{

}

class Company{
    -designation : String
}

class VaccineTypeStore{

}

class VaccineStore{

}

class Vaccine{
    -designation : String
    -numberOfAgeGroups : int
}

class VaccineType{
    -code : int
    -description : String
    -tecnhology : String
}

class AdminProc{
    -numberOfDoses : int
    -minAge : int
    -maxAge : int
}

class AdminProcList{

}

class DoseInfo{
    -dosage : int
    -timeToNextDose : int
}

class DoseInfoList{

}

CreateVaccineUI ..> CreateVaccineController
CreateVaccineController ..> VaccineStore
CreateVaccineController ..> VaccineTypeStore
CreateVaccineController ..> Company
VaccineStore ..> Company
VaccineTypeStore ..> Company
Company -> Vaccine
Vaccine -> AdminProcList
AdminProcList -> AdminProc
AdminProc -> DoseInfoList
DoseInfoList -> DoseInfo

@enduml