@startuml US17_SD
autonumber

actor "Center Coordinator" as COORDINATOR

participant ":ImportLegacyDataUI" as UI
participant ":App" as APP
participant ":ImportLegacyDataController" as CTRL

activate COORDINATOR
  COORDINATOR -> UI : starts to import legacy data
  activate UI
    UI -> APP : company = getCompany()
    activate APP
    deactivate APP

    
  deactivate UI
deactivate COORDINATOR
@enduml
