@startuml US17_SD
autonumber

actor "Center Coordinator" as COORDINATOR

participant ":CoordinatorUI" as CUI
participant ":ImportLegacyDataUI" as UI
participant "App" as _APP
participant "app:App" as APP
participant ":ImportLegacyDataController" as CTRL
participant "empSess:employeeSession" as SESSION
participant "comp:Company" as COMPANY
participant "csvReader:CSVReader" as CSVREADER
participant ":ICSVReader" as ICSV
participant ":LegacyDataMapper" as MAPPER
participant "legacyDataDto:LegacyDataDTO" as DTO
participant "legacyDtoList:List<LegacyDataDTO>" as LIST_DTOS
participant "legacyDataObjectBuilder:LegacyDataObjectBuilder" as BUILDER
participant "legacyData:LegacyData" as LEGACYDATA
participant "snsUserStore:SNSUserStore" as SNSSTORE
participant "snsUser:SNSUser" as SNSUSER
participant "center:VaccinationCenter" as CENTER
participant "waitingRoom:WaitingRoom" as WR
participant "aptSchLst:AppointmentScheduleList" as APTSCHLST
participant "centerEventList:CenterEventList" as CELIST
participant ":SortFactory" as SORTFACTORY
participant "sortStrategy:ISortStrategy" as ISORTSTRATEGY
participant "vacStore:VaccineStore" as VACCINESTORE
participant "vaccine:Vaccine" as VACCINE
participant "administrationList:AdministrationList" as ADLST
participant "appointment:Appointment" as APT
participant "arrival:Arrival" as ARRIVAL
participant "vacAdministration:VaccineAdministration" as VACADMINISTRATION
participant "fileData:List<String[]>" as LIST_FILEDATA

activate COORDINATOR
  ref over COORDINATOR
    ' !include ../../CoordinatorLogin_SD.puml!
    ' ![[../../CoordinatorLogin_SD.puml]]
    ' ![[../../CoordinatorLogin_SD.svg]]
    CoordinatorLogin_SD
  end ref

  activate CUI
  COORDINATOR -> CUI : starts the process of importing data from a legacy system

      note right of CUI
        employeeSession has <i><b>center</b></i> obtained 
        during Coordinator login.
      end note

      |||

    CUI -> SESSION : center = getVaccinationCenter()
    activate SESSION
    deactivate SESSION

    CUI -> UI ** : create(center)
    activate UI

      UI -> _APP : app = getInstance()
      activate _APP
      deactivate _APP

      UI -> APP : company = getCompany()
      activate APP
      deactivate APP

      UI -> CTRL ** : create(company, center)
      activate CTRL
        CTRL -> COMPANY : snsUserStore = getSNSUserStore()
        activate COMPANY
        deactivate COMPANY
      deactivate CTRL
      
      COORDINATOR <-- UI : asks for the file that should be loaded
    deactivate UI

    COORDINATOR -> UI : selects the file
    activate UI
    
      ' read data

      UI -> CTRL : fileData = read(filepath)
      activate CTRL
        CTRL -> CSVREADER ** : create(filepath)

        CTRL -> CSVREADER : read()
        activate CSVREADER
          CSVREADER -> ICSV ** : newInstance(filepath)
          CSVREADER -> ICSV : read(fileData)
          activate ICSV
          deactivate ICSV
        deactivate CSVREADER

      deactivate CTRL

      ' process data
      UI -> CTRL : legacyDtoList = convert(fileData)
      activate CTRL
        loop for each entry in fileData
          CTRL -> MAPPER : dto = toDto(entry)
          activate MAPPER
            MAPPER -> DTO : create(snsNumber, vaccineName, dose, lotNumber, scheduledDate, arrivalDate, administrationDate, leavingDate)
            activate DTO
            deactivate DTO
          deactivate MAPPER

          CTRL -> LIST_DTOS : add(dto)
          activate LIST_DTOS
          deactivate LIST_DTOS
        end
      deactivate CTRL

      UI -> CTRL : validate(legacy)
      activate CTRL
        loop for each legacyDataDto in legacyDtoList
          CTRL -> DTO : snsNumber = getSNSNumber()
          activate DTO
          deactivate DTO

          CTRL -> SNSSTORE : b = findSNSUserByNumber(snsNumber)
          activate SNSSTORE
          deactivate SNSSTORE
        end
      deactivate CTRL

      UI -> CTRL : sort(legacy)
      activate CTRL
        ' TODO: sort with strategy pattern
        CTRL -> SORTFACTORY : sortStrategy = getSortStrategy()
        activate SORTFACTORY
        deactivate SORTFACTORY
        
        CTRL -> ISORTSTRATEGY : doSort(legacyDtoList)
        activate ISORTSTRATEGY
        deactivate ISORTSTRATEGY
      deactivate CTRL

      ' convert to list dto and send it to ui

      COORDINATOR <-- UI : opens the file and shows data sorted
    deactivate UI

    COORDINATOR -> UI : confirms the data
    activate UI
      UI -> CTRL : save(legacy)
      activate CTRL
        ' CTRL -> COMPANY : vacStore = getVaccineStore()
        ' activate COMPANY
        ' deactivate COMPANY

        CTRL -> CENTER : aptSchLst = getAppointmentScheduleList()
        activate CENTER
        deactivate CENTER

        CTRL -> CENTER : wrLst = getWaitingRoomList()
        activate CENTER
        deactivate CENTER

        CTRL -> CENTER : centerEventList = getCenterEventList()
        activate CENTER
        deactivate CENTER

        loop for each legacyDataDto in legacyDtoList
          ' builder
          CTRL -> MAPPER : legacyData = toModel(legacyDataDto)
          activate MAPPER
          deactivate MAPPER

          CTRL -> LEGACYDATA : getSnsUser()
          activate LEGACYDATA
          deactivate LEGACYDATA

          CTRL -> SNSUSER : getAdministrationList()
          activate SNSUSER
          deactivate SNSUSER

          CTRL -> BUILDER : create(legacyData, center)
          activate BUILDER
          deactivate BUILDER

          note right of CTRL
            <i><b>LegacyDataObjectBuilder</b></i> is responsible for creating
            instances of the classes needed.
          end note

          CTRL -> BUILDER : appointment = createAppointment()
          activate BUILDER
          deactivate BUILDER

          CTRL -> APTSCHLST : saveAppointment(appointment)
          activate APTSCHLST
          deactivate APTSCHLST

          CTRL -> BUILDER : arrival = createArrival()
          activate BUILDER
          deactivate BUILDER

          CTRL -> WR : saveArrival(arrival)
          activate WR
          deactivate WR

          CTRL -> BUILDER : vacAdministration = createVaccineAdministration()
          activate BUILDER
          deactivate BUILDER

          CTRL -> VACADMINISTRATION : saveVaccineAdministration(vacAdministration)
          activate VACADMINISTRATION
          deactivate VACADMINISTRATION

          CTRL -> BUILDER : arrivalEvent = createArrivalEvent()
          activate BUILDER
          deactivate BUILDER

          CTRL -> CELIST : save(arrivalEvent)
          activate CELIST
          deactivate CELIST

          CTRL -> BUILDER : vaccinatedEvent = createVaccinatedEvent()
          activate BUILDER
          deactivate BUILDER

          CTRL -> CELIST : save(vaccinatedEvent)
          activate CELIST
          deactivate CELIST

          CTRL -> BUILDER : departuredEvent = createDeparturedEvent()
          activate BUILDER
          deactivate BUILDER

          CTRL -> CELIST : save(departuredEvent)
          activate CELIST
          deactivate CELIST

          
        end
      deactivate CTRL
      COORDINATOR <-- UI : informs operation success
    deactivate UI

  deactivate CUI
deactivate COORDINATOR
@enduml
