@startuml US15_SSD
autonumber
actor "Center Coordinator" as COOR

activate COOR
COOR -> ":System" : asks to export his center statistics
activate ":System"
":System" --> COOR : requests data (filePath,startDate,endDate)
deactivate ":System"

COOR -> ":System" : types requested
activate ":System"

":System" --> COOR : informs operation success
deactivate ":System"
deactivate COOR

@enduml