@startuml US04_CD
skinparam classAttributeIconSize 0

class RegisterSNSUserArrivalUI {}

class RegisterSNSUserArrivalController {}

class Company {
  - String designation
  + getDesignation()
}

class SNSUser {
  - String citizenCard
  - String snsNumber
  - Date birthDay
  - Char gender
  - String phoneNumber
  - String address
  + SNSUser(citizenCard, snsNumber, name, birthDay, gender, phoneNumber, email, address)
}

class SNSUserStore {
  + createUser(name, email, pwd, roleId)
  + validateUser(user)
  + saveUser(user)
  + checkDuplicates(user)
}

class Employee {
  - id: String
  - address: String
  - phoneNumber: String
  - citizenCardNumber: String
  + Employee(id, name, address, phoneNumber, email, citizenCardNumber, roleId)
  + getId()
  + getName()
  + getAddress()
  + getPhoneNumber()
  + getEmail()
  + getCitizenCardNumber()
  + getPassword()
  + getRoleId()
}

class Receptionist {}

class Arrival {
  - Date arrivalDate
}

class Appointment {}

class WaitingRoomList {}

class VaccinationCenterStore {
  ---
  + createVaccinationCenter(centerData, coordinator)
  + validateVaccinatonCenter(center)
  + saveVaccinationCenter(center)
  + checkDuplicates(center)
  + addVaccinationCenter(center)
}

class VaccinationCenter {
  - name: String
  - address: String
  - emailAddress: String
  - phoneNumber: String
  - faxNumber: String
  - websiteAddress: String
  - openingHours: String
  - closingHours: String
  - slotDuration: int
  - maximumVaccinesPerSlot: int
  - coordinator: EMPLOYEE
  ---
  + VaccinationCenter(name,address,emailAddress,phoneNumber,faxNumber,websiteAddress,openingHours,closingHours,slotDuration,maximumVaccinesPerSlot,coordinator)
}

Arrival "1" --> "0..1" Appointment : has

Company ..> SNSUserStore
Company ..> VaccinationCenterStore
Company "1" --> "*" SNSUser : knows
Company "1" --> "*" Employee : knows

Employee "1" --> "1" Receptionist : plays as

Receptionist ..> Arrival

RegisterSNSUserArrivalController ..> Company

RegisterSNSUserArrivalUI ..> RegisterSNSUserArrivalController

SNSUserStore "1" --> "*" SNSUser : stores
VaccinationCenterStore "1" --> "*" VaccinationCenter : stores

VaccinationCenter "1" --> "1" WaitingRoomList : has

SNSUser ..> Arrival
SNSUser ..> Appointment

WaitingRoomList "1" --> "*" SNSUser : has

@enduml