@startuml
autonumber
'hide footbox
actor "Nurse" as NURSE

participant ":ListUsersInWaitingRoomUI" as UI
participant ":ListUsersInWaitingRoomController" as CTRL
participant ":NurseSessionFacade" as FAC
participant "comp\n:Company" as COMP
participant "vaccinationCenterStore\n:VaccinationCenterStore" as VACS
participant ":VaccinationCenterMapper" as VACM
participant ":AppointmentMapper" as APOM
participant "appointment:Appointment" as APO

activate NURSE
NURSE -> UI : asks to list users in waiting room for a given vaccination center
activate UI

UI -> CTRL : getWaitingRoomListFromNurseCenter()
activate CTRL
CTRL -> FAC : nurseVaccinationCenterId=getNurseVaccinationCenterId()
activate FAC
deactivate FAC
|||

CTRL -> VACS : waitingRoom=getCenterWaitingRoom(nurseVaccinationCenterId)
activate VACS
deactivate VACS

CTRL -> APOM : waitingRoomDto=toDto(waitingRoom)
activate APOM

create "waitingRoomDto:\nList<AppointmentDto>" as WAITDTO

APOM -> WAITDTO

loop for each appointment in waitingRoom
|||
  APOM -> APO : username=appointment.getUserName()
  APOM -> APOM : placeInLine=i

  create "AppointmentDto\n:AppointmentDto" as APODTO
  APOM -> APODTO : create(username, i)

  APOM -> WAITDTO : add(appointmentDto)
|||
end

|||
APOM --> CTRL : appointmentDto 

deactivate APOM

CTRL --> UI: waitingRoomDto

deactivate COMP
deactivate CTRL
UI --> NURSE : informs operation success
UI --> NURSE: shows list of users waiting in vaccination center
deactivate UI

deactivate UI
deactivate CTRL
deactivate NURSE

participant "vaccinationCenters:\nList<VaccinationCenter>"
participant "vaccinationCentersDto:\nList<VaccinationCenterDTO>"
participant "waitingRoom:\nList<Appointment>"

@enduml
