@startuml
autonumber
'hide footbox
actor "Nurse" as NURSE

participant ":ListUsersInWaitingRoomUI" as UI
activate NURSE
NURSE -> UI : asks to list users in waiting room for a given vaccination center
activate UI
participant ":App" as APP
UI -> APP : app=getInstance()
activate APP
deactivate APP
UI -> APP : company=app.getCompany()
activate APP
deactivate APP

create ":ListUsersInWaitingRoomController" as CTRL

UI -> CTRL : create(company,nurseSession)

participant "nurseSession\n:NurseSession" as FAC
participant "comp\n:Company" as COMP
participant "vaccinationCenterStore\n:VaccinationCenterStore" as VACS
participant ":ArriveMapper" as ARRM
participant "arriveHistory\n:ArriveHistory" as ARR
participant "arrive:Arrive" as ARR


UI -> CTRL : getWaitingRoomListFromNurseCenter()
activate CTRL
CTRL -> FAC : nurseVaccinationCenter=getVaccinationCenter()
activate FAC
deactivate FAC
|||

CTRL -> COMP : vaccinationCenterStore=getVaccinationCenterStore()
activate COMP
deactivate

CTRL -> VACS : waitingRoom=getCenterWaitingRoom(nurseVaccinationCenter)
activate VACS
deactivate VACS

CTRL -> ARRM : waitingRoomDto=toDto(waitingRoom)
activate ARRM

create "waitingRoomDto:\nList<ArriveDto>" as WAITDTO

ARRM -> WAITDTO

loop for each arrive in waitingRoom
|||
  ARRM -> ARRM : placeInLine=i
  ARRM -> ARR : username=arrive.getUserName()
  activate ARR
  deactivate ARR
  ARRM -> ARR : arriveTime=arrive.getArriveTime()
  activate ARR
  deactivate ARR

  create "arriveDto\n:ArriveDto" as APODTO
  ARRM -> APODTO : create(placeInLine,username,arriveTime)

  ARRM -> WAITDTO : add(arriveDto)
  activate WAITDTO
  deactivate WAITDTO
|||
end

|||
ARRM --> CTRL : waitingRoomDto 

deactivate ARRM

CTRL --> UI: waitingRoomDto

deactivate COMP
deactivate CTRL
UI --> NURSE: shows list of users waiting in vaccination center
deactivate UI

deactivate UI
deactivate CTRL
deactivate NURSE

participant "vaccinationCenters:\nList<VaccinationCenter>"
participant "vaccinationCentersDto:\nList<VaccinationCenterDTO>"
participant "waitingRoom:\nList<Appointment>"

@enduml
