@startuml
autonumber
'hide footbox
actor "Administrator" as ADM

participant ":CreateVaccineUI" as UI
participant ":CreateVaccineController" as CTRL
participant "Company" as COMP
participant "vac : Vaccine" as VAC
participant "adminProc : AdministrationProcess" as AP
participant "DoseInfo : DoseInformation" as DI
participant "vacT : VaccineType" as VACT

activate ADM

ADM -> UI : asks to create a new vaccine
activate UI
UI --> ADM :  requests data (designation, number of different age groups)
deactivate UI

ADM -> UI : types requested data
activate UI
    UI -> CTRL : vacTypeList = getVacTypeList()
    activate CTRL

        CTRL -> COMP : vacTypeList = getVacTypeList()
        activate COMP 
        |||
        COMP --> CTRL : vacTypeList
        deactivate COMP
        CTRL --> UI : vacTypeList
    deactivate CTRL
UI --> ADM : shows vaccine types list and ask to select one
deactivate UI

ADM -> UI : selects a vaccine type
activate UI
    UI -> CTRL : vac = creatVaccine(designation, numberAgeGroups, vacType)
    activate CTRL

        CTRL -> COMP : vac = creatVaccine(designation, numberAgeGroups, vacType)
        activate COMP 

            COMP -> VAC ** : creat(designation, numberAgeGroups, vacType)

        deactivate COMP

        CTRL -> COMP : validateVaccine(vac)
        activate COMP 
            COMP -> COMP : checkDuplicatedDesignation(designation)
        deactivate COMP

    deactivate CTRL
UI --> ADM : informs that is ready to move on to the administration processes specification
deactivate UI


loop for each age group

    ADM -> UI : asks to create a new administration process for the vaccine
    activate UI
    UI --> ADM : requests data (minAge, maxAge, numberOfDoses)
    deactivate UI

    ADM -> UI : types requested data
    activate UI
        UI -> CTRL : adminProc = creatAdminProc(minAge, maxAge, numberOfDoses)
        activate CTRL

            CTRL -> COMP : adminProc = creatAdminProc(minAge, maxAge, numberOfDoses)
            activate COMP 

                COMP -> AP ** : creat(designation, numberAgeGroups, vacType)

            deactivate COMP

            CTRL -> COMP : validateAdminProc(adminProc)
            activate COMP 
            deactivate COMP

        deactivate CTRL
    UI --> ADM : informs that is ready to move on to the dose information
    deactivate UI

    loop for each dose

        ADM -> UI : asks to add dose information to the administration process
        activate UI
        UI --> ADM : requests data (dosage, timeToNextDose)
        deactivate UI
        ADM -> UI : types requested data
        activate UI
            UI -> CTRL : doseInfo = creatDoseInfo(dosage, timeToNextDose)
                activate CTRL
                CTRL -> COMP : doseInfo = creatDoseInfo(dosage, timeToNextDose)
                activate COMP 

                    COMP -> DI ** : creat(dosage, timeToNextDose)

                deactivate COMP

                CTRL -> COMP : validateDoseInfo(doseInfo)
                activate COMP 
                deactivate COMP

                deactivate CTRL
        UI --> ADM : informs dose information specification sucess
        deactivate UI
    end
end
ADM -> UI : asks to confirm all data
activate UI
UI --> ADM : shows all data and requests confirmation
deactivate UI

ADM -> UI : confirms the data
activate UI
UI -> CTRL : saveVaccine()
    activate CTRL

        CTRL -> COMP :  saveVaccine(vac)
        activate COMP 
            COMP -> COMP : validateVaccine(vac)
            COMP -> COMP : addVaccine(vac)
            COMP --> CTRL : result
        deactivate COMP
        CTRL --> UI : result
    deactivate CTRL
UI --> ADM : informs operation success
deactivate UI

deactivate ADM

@enduml