@startuml
autonumber
'hide footbox
actor "Administrator" as ADM

participant ":CreateVaccineUI" as UI
participant ":CreateVaccineController" as CTRL
participant "Company" as COMP
participant "vacTSt : VaccineTypeStore" as VACT_ST
participant "vacSt : VaccineStore" as VAC_ST
participant "vac : Vaccine" as VAC
participant "adminProc : AdminProc" as AP
participant "adminPLst : AdminProcList" as AP_LST
participant "doseInfo : DoseInfo" as DI
participant "doseInfoLst : DoseInfoList" as DI_LST

activate ADM

ADM -> UI : asks to create a new vaccine
activate UI
    UI -> CTRL : vacTLst = getVacTypes()
    activate CTRL
        CTRL -> COMP : vacTSt = getVaccineTypeStore()
        activate COMP 
        |||
        deactivate COMP
    deactivate CTRL
    UI -> CTRL : vacLst = getVaccines()
    activate CTRL
        CTRL -> COMP : vacSt = getVaccineStore()
        activate COMP 
        |||
        deactivate COMP
    deactivate CTRL
UI --> ADM :  requests data (designation, id, brand, numberOfAgeGroups) and shows vaccine types list to select one
deactivate UI

ADM -> UI : types requested data
activate UI
    UI -> CTRL : vac = createVaccine(designation, brand, id, numberAgeGroups, vacTypeId)
    activate CTRL

        CTRL -> VACT_ST : vacType = getVacTypeId(vacTypeId)
        activate VACT_ST 
        deactivate VACT_ST
        CTRL -> VAC_ST : vac = createVaccine(designation, brand, id, numberAgeGroups, vacType)
        activate VAC_ST 
            VAC_ST -> VAC ** : create(designation, brand, id, numberAgeGroups, vacType)
            VAC -> AP_LST ** 
            AP_LST -> DI_LST **
        deactivate VAC_ST

        CTRL -> VAC_ST : validateVaccine(vac)
        activate VAC_ST 
            VAC_ST -> VAC_ST : checkDuplicatedDesignation(designation)
            activate VAC_ST 
            deactivate VAC_ST
        deactivate VAC_ST

    deactivate CTRL
UI --> ADM : informs that is ready to move on to the administration processes specification
deactivate UI


loop for each age group

    ADM -> UI : asks to create a new administration process for the vaccine
    activate UI
    UI --> ADM : requests data (minAge, maxAge, numberOfDoses)
    deactivate UI

    ADM -> UI : types requested data
    activate UI
        UI -> CTRL : adminProc = createAdminProc(minAge, maxAge, numberOfDoses)
        activate CTRL

            CTRL -> VAC : adminProc = createAdminProc(minAge, maxAge, numberOfDoses)
            activate VAC

                VAC -> AP ** : create(minAge, maxAge, numberOfDoses)

            deactivate VAC

            CTRL -> VAC : validateAdminProc(adminProc)
            activate VAC
            deactivate VAC

        deactivate CTRL
    UI --> ADM : shows age group data and request confirmation
    deactivate UI
    ADM -> UI : confirms data
    activate UI
    UI -> CTRL : saveAdminProc()
    activate CTRL
        CTRL -> AP_LST : addAdminProc(adminProc)
        activate AP_LST
        deactivate AP_LST
    deactivate CTRL
    UI --> ADM :  informs operation sucess
    deactivate UI

    loop for each dose

        ADM -> UI : asks to add dose information to the administration process
        activate UI
        UI --> ADM : requests data (dosage, TimeSinceLastDose)
        deactivate UI
        ADM -> UI : types requested data
        activate UI
            UI -> CTRL : doseInfo = createDoseInfo(dosage, TimeSinceLastDose)
                activate CTRL
                CTRL -> AP : doseInfo = createDoseInfo(dosage, TimeSinceLastDose)
                activate AP

                    AP -> DI ** : create(dosage, TimeSinceLastDose)

                deactivate AP

                CTRL -> AP : validateDoseInfo(doseInfo)
                activate AP 
                deactivate AP

                deactivate CTRL
         UI --> ADM : shows dose information data and request confirmation
        deactivate UI
        ADM -> UI : confirms data
        activate UI
        UI -> CTRL : saveDoseInfo()
        activate CTRL
        CTRL -> DI_LST : addDoseInfo(doseInfo)
        activate DI_LST
        deactivate DI_LST
        deactivate CTRL
        UI --> ADM :  informs operation sucess
        deactivate UI
    end
end
ADM -> UI : asks to confirm all data
activate UI
UI --> ADM : shows all data and requests confirmation
deactivate UI

ADM -> UI : confirms the data
activate UI
UI -> CTRL : saveVaccine()
    activate CTRL

        CTRL -> VAC_ST :  saveVaccine(vac)
        activate VAC_ST 
            VAC_ST -> VAC_ST : validateVaccine(vac)
            activate VAC_ST 
            deactivate VAC_ST
            VAC_ST -> VAC_ST : addVaccine(vac)
            activate VAC_ST 
            deactivate VAC_ST
        deactivate VAC_ST
        CTRL --> UI : result
    deactivate CTRL
UI --> ADM : informs operation success
deactivate UI

deactivate ADM

@enduml 