@startuml
autonumber
actor "Administrator" as OE

activate OE
OE -> ":System" : asks to create a new vaccine
activate ":System"
":System" --> OE : requests data (designation, age groups interval limits, number of dosages, dosages, time interval limits between doses)
deactivate ":System"

OE -> ":System" : types requested data
activate ":System"
":System" --> OE : shows task vaccine types list and ask to select one
deactivate ":System"

OE -> ":System" : selects a task vaccine type
activate ":System"
":System" --> OE : shows all data and requests confirmation
deactivate ":System"

OE -> ":System" : confirms the data
activate ":System"
":System" --> OE : informs operation success
deactivate ":System"

deactivate OE

@enduml