@startuml
autonumber
actor "Administrator" as OE

activate OE
OE -> ":System" : asks to create a new vaccine
activate ":System"
":System" --> OE : requests data (designation, id, brand) and shows vaccine types list to select one
deactivate ":System"

OE -> ":System" : types requested data
activate ":System"
":System" --> OE : informs that is ready to move on to the administration processes specification
deactivate ":System"

loop for each age group
    OE -> ":System" : asks to create a new administration process for the vaccine
    activate ":System"
    ":System" --> OE : requests data (minAge, maxAge)
    deactivate ":System"
    OE -> ":System" : types requested data
    activate ":System"
    ":System" --> OE : shows age group data and request confirmation
    deactivate ":System"
    OE -> ":System" : confirms data
    activate ":System"
    ":System" --> OE : informs operation sucess
    deactivate ":System"
    
    loop for each dose
        OE -> ":System" : asks to add dose information to the administration process
        activate ":System"
        ":System" --> OE : requests data (dosage, timeSinceLastDose)
        deactivate ":System"
        OE -> ":System" : types requested data
        activate ":System"
        ":System" --> OE : shows dose information data and request confirmation
        deactivate ":System"
        OE -> ":System" : confirms data
        activate ":System"
        ":System" --> OE : informs operation sucess
        deactivate ":System"
    end

end

OE -> ":System" : asks to confirm all data
activate ":System"
":System" --> OE : shows all data and requests confirmation
deactivate ":System"
OE -> ":System" : confirms the data
activate ":System"
":System" --> OE : informs operation success
deactivate ":System"

deactivate OE

@enduml