@startuml PackageDiagram
package core {
    package Controllers {}
    package UI {
        package GUI {}
        package Console {}
    }
    package Domain {
        package model {
            package store {}
            package list {}
        }
        package shared {}
    }
    package Dto {}
    package Mappers {}
    package Exception {}
    package Utils {}
    package Session {}
    package Service {}
}

Console ..> GUI

Controllers ..> Mappers
Controllers ..> Domain

UI ..> Controllers

Domain ..> Mappers
Domain ..> Utils
Domain ..> Exception
Domain ..> Service
Domain ..> Session

Mappers ..> Dto

@enduml