@startuml CoordinatorLogin_SD

actor "Center Coordinator" as COORDINATOR

note over COORDINATOR
 After logging in successfully
end note

participant ":AuthUI" as AUTHUI
participant ":CoordinatorUI" as EUI
' participant ":FindCoordinatorVaccinationCenterUI" as UI
participant ":FindCoordinatorVaccinationCenterController" as CTRL
participant "employeeSession\n:EmployeeSession" as SESSION
participant "company\n:Company" as COMP
participant "vaccinationCenterStore\n:VaccinationCenterStore" as VACCS
' participant "centerDTO\n:VaccinationCenterListDTO" as CDTO
participant "company\n:Company" as COMP
participant ":App" as _APP
participant "app:App" as APP
participant "vaccinationCenter\n:VaccinationCenter"
' participant "vaccinationCenters\n:List<VaccinationCenterListDTO>"

activate AUTHUI
AUTHUI -> EUI **
activate EUI
EUI -> SESSION **
' EUI -> UI **
' AUTHUI -> UI : run()
' activate UI
activate COORDINATOR


EUI -> _APP : app=getInstance()
activate _APP
deactivate _APP

EUI -> APP : company=getCompany()
activate APP
deactivate APP


EUI -> CTRL ** : create(company,employeeSession)
activate CTRL
CTRL -> COMP : vaccinationCenterStore=getVaccinationCenterStore()
activate COMP
deactivate COMP
deactivate CTRL

EUI -> CTRL : vaccinationCenter=findCoordinatorCenter()
activate CTRL

CTRL -> SESSION : email = getEmail()
activate SESSION
deactivate SESSION

CTRL -> VACCS : getVaccinationCenterWithCoordinatorEmail(email)
activate VACCS
deactivate VACCS

CTRL -> SESSION : setVaccinationCenter(vaccinationCenter)
activate SESSION
deactivate SESSION

deactivate CTRL


' AUTHUI -> CTRL 
' deactivate UI
' CTRL -> CDTO : email=getEmail()
' activate CDTO
' deactivate CDTO
' CTRL -> VACCS : vaccinationCenter=getVaccinationCenterWithEmail(email)
' activate VACCS
' deactivate VACCS
' CTRL -> SESSION : setVaccinationCenter(vaccinationCenter)
' activate SESSION
' deactivate SESSION
' deactivate EUI



deactivate CTRL

' deactivate UI

deactivate COORDINATOR

' |||

note over COORDINATOR
  The employee vaccination center is stored in the EmployeeSession
end note
@enduml
