@startuml DM

hide methods
left to right direction
skinparam classAttributeIconSize 0

class Company {
  - designation
}

class CommunityMassVaccinationCenter {}

class HealthCareCenter {}

class VaccinationCenter {
  -name
  -emailAddress
  -phone
  -email
  -fax
  -website
  -openingHours
  -closingHours
}

class Vaccine {
  -designation
  -id
  -brand
}

class VaccineType {
  -code 
  -description
  -technology
}

class SNSUser {
  - citizenCard
  - snsNumber
  - name
  - birthDay
  - gender
  - phoneNumber
  - email
}

class UserHealthData {}

class Administrator {}

class Employee {
  -name
  -phoneNumber
  -email
  -password
  -address
  -citizenCardNumber
  -roleId
}

class Nurse {}

class Receptionist {}

class CenterCoordinator {}

class Appointment {
  -date
  -sms
}

class VaccineAdministration {
  -lotNumber
  -doseNumber
  -date
}

class AdministrationProcess {
  -ageGroup
  -nOfDoses
}

class AGES {}

class ARS {}

class DoseInformation {
  -dosage
  -timeToNextDose
  -doseNumber
}

class Slot {
  -slotDuration
  -maxVacPerSlot
}

class Notification {}

class Arrival {
  - arrivalDate
}

class WaitingRoom {}

class Address {
  -street
  -doorNumber
  -postalCode
  -city
}

Address "1" -- "*" Employee : has <
Address "1" -- "*" VaccinationCenter : has <
Address "1" -- "*" SNSUser : has <

Arrival "1" -- "0..1" Appointment : related to >
Arrival "*" -- "*" WaitingRoom : is in >

DoseInformation "*" -- "1" AdministrationProcess : has <

Vaccine "*" -- "1" VaccineType : has <

Employee <|-- Nurse
Employee <|-- Receptionist
Employee <|-- CenterCoordinator

VaccinationCenter <|-- CommunityMassVaccinationCenter
VaccinationCenter <|-- HealthCareCenter

VaccinationCenter "1" -- "1" CenterCoordinator : has < 
VaccinationCenter "1" -- "1" Slot : has >

HealthCareCenter "*" -- "1" AGES : belongs to > 
HealthCareCenter "*" -- "1" ARS : belongs to > 

Appointment "*" -- "1" VaccinationCenter : is held in >
Appointment "1" -- "1" VaccineType : has a specific >
Appointment "1" -- "0..1" Notification : triggers >

Receptionist "1" -- "*" SNSUser : registers >

Administrator "1" -- "*" Employee : registers >
Administrator "1" -- "*" VaccinationCenter : registers >
Administrator "1" -- "*" VaccineType : manages >
Administrator "1" -- "*" Vaccine : manages > 

Vaccine "1" -- "1..*" AdministrationProcess : has >

SNSUser "1" -- "*" Appointment : schedules >
SNSUser "1" -- "*" Arrival : associated to >
SNSUser "1" -- "1" UserHealthData : has >
SNSUser "1" -- "*" Notification : receives >
SNSUser "1" -- "*" VaccineAdministration : associated to >

Company "1" -- "*" Employee : knows >
Company "1" -- "*" VaccinationCenter : knows >
Company "1" -- "*" SNSUser : knows >
Company "1" -- "*" Administrator : knows >

Receptionist "0..1" -- "1" Appointment : schedules >
Receptionist "1" -- "*" Appointment : related to >
Receptionist "1" -- "*" Arrival : registers >

Nurse "1" -- "*" AdverseReaction : reports >
Nurse "1" -- "*" UserHealthData : checks >
Nurse "1" -- "*" VaccineAdministration : registers >

VaccinationCenter "1" -- "1" WaitingRoom : has >

Nurse "1" -- "*" AdministrationProcess : checks >

Notification <|-- SMSSender
Notification <|-- EmailSender
Notification <|-- ConsoleSender

AdverseReaction "*" -- "1" Appointment : has <

VaccineAdministration "*" -- "1" Vaccine : has >
VaccineAdministration "*" -- "1" VaccinationCenter : is held in >

UserHealthData "1" -- "*" VaccineAdministration : has >

@enduml
