@startuml  US02_DM
hide methods
skinparam classAttributeIconSize 0


class Appointment {}

class VaccineType {}

class SNSUser {
  - citizenCard
  - snsNumber
  - name
  - birthDay
  - gender
  - phoneNumber
  - email
  - address
}

class VaccinationCenter{
  -name
  -address
  -emailAddress
  -phoneNumber
  -faxNumber
  -websiteAddress
  -openingHours  
  -closingHours
  -slotDuration
  -maximumVaccinesPerSlot
  -coordinator
}

class Company{
  -designation
}

class Receptionist {}

class Employee {}

class Vaccine {
  -designation
  -brand
  -id
  -vaccineType
}

Company "1" -- "*" Appointment : knows >
Appointment "1"  -- "1" Vaccine : has >
Appointment "*" -- "1" VaccinationCenter : has >
Company "1" -- "*" VaccinationCenter : knows >
Appointment "*" -- "1" Receptionist : scheduled by >
Receptionist "1" -- "1" SNSUser : schedules for >
Appointment "1" -- "1" SNSUser : has >
Employee "1" -- "0..1" Receptionist : play as >
Company -- Employee : knows >
Vaccine "1" -- "*" VaccineType : part of <


@enduml