@startuml DM

hide methods
left to right direction
skinparam classAttributeIconSize 0

class Company {
  - designation
}

class CommunityMassVaccinationCenter {}

class HealthCareCenter {}

class VaccinationCenter {
  name
  address
  emailAddress
  phone
  email
  fax
  website
}

class Vaccine {}

class VaccineType {
  id
  designation
  whoid
}

class SNSUser {
  - citizenCard
  - snsNumber
  - name
  - birthDay
  - gender
  - phoneNumber
  - email
  - address
}

class User {
  - name
  - email
  - pwd
  - role
}

class HealthInformation {}

class Administrator {}

class Employee {}

class Nurse {}

class Receptionist {}

class CenterCoordinator {}

class Appointment {
  snsUser
  date
  vaccinationCenter
  vaccineType
  sms
}

class AdministrationProccess {
  ageGroup
  nOfDoses
}

class AGES {}

class ARS {}

class DoseInformation {
  dosage
  timeToNextDose
  doseNumber
}

class Slot {
  slotDuration
  maxVacPerSlot
}

class Time {
  openingHours
  closingHours
}

DoseInformation "*" -- "1" AdministrationProccess : has <

Vaccine "*" -- "1" VaccineType : has <

Employee <|-- Nurse
Employee <|-- Receptionist
Employee <|-- CenterCoordinator

VaccinationCenter <|-- CommunityMassVaccinationCenter
VaccinationCenter <|-- HealthCareCenter

VaccinationCenter "1" -- "1" CenterCoordinator : has < 
VaccinationCenter "1" -- "1" Slot : has >
VaccinationCenter "1" -- "1" Time : has >

HealthCareCenter "*" -- "1" AGES : belongs to > 
HealthCareCenter "*" -- "1" ARS : belongs to > 

Appointment "*" -- "1" VaccinationCenter : is held in >
Appointment "1" -- "1" VaccineType : has a specefic >
Appointment "1" -- "0..1" SMSSender : triggers >
Appointment "1" -- "0..1" EmailSender : triggers >

Receptionist "1" -- "*" WaitingRoom : manages >
Receptionist "1" -- "*" ArrivedUsersList : manages >
Receptionist "1" -- "*" SNSUser : registers >

WaitingRoom "1" -- "*" SNSUser : is composed by >
ArrivedUsersList "1" -- "*" SNSUser : is composed by > 
RecoveringUsersList "1" -- "*" SNSUser : is composed by >

WaitingRoom "*" -- "1" Nurse : checks <
RecoveringUsersList "*" -- "1" Nurse : manages <

Administrator "1" -- "*" Employee : registers >
Administrator "1" -- "*" VaccinationCenter : registers >
Administrator "1" -- "*" VaccineType : manages >
Administrator "1" -- "*" Vaccine : manages > 

Vaccine "1" -- "1..*" AdministrationProccess : has >

SNSUser "1" -- "*" Appointment : schedules >
SNSUser "1" -- "1" HealthInformation : has >
SNSUser "1" -- "*" Notification : receives >
SNSUser "1" -- "*" VaccinationCertificate : requests >
SNSUser "0..1" -- "1" User : becomes >


VaccinationCertificate "1" -- "1" Vaccine : corresponds >

Company "1" -- "*" VaccinationCertificate : emmits >
Company "1" -- "*" Employee : knows >
Company "1" -- "*" VaccinationCenter : knows >

Receptionist "0,1" -- "1" Appointment : schedules >

Nurse "1" -- "*" AdverseReaction : reports >
Nurse "1" -- "*" HealthInformation : checks >

VaccinationCenter "1" -- "1" VaccinationReport : has >
CenterCoordinator "1" -- "*" VaccinationReport : analyses >
CenterCoordinator "1" -- "*" VaccinationReport : generates >

Nurse "1" -- "*" AdministrationProccess : checks >

AdverseReaction "*" -- "1" Appointment : has <

@enduml
